//GITGJOB JOB (12345),'GITGALAXY FORGE',
//             CLASS=A,MSGCLASS=A,MSGLEVEL=(1,1),
//             USER=HERC01,PASSWORD=CUL8TR,
//             TIME=10,REGION=4M
//* ==========================================================
//* AUTOGENERATED BY GITGALAXY ZERO-TRUST FORGE
//* ==========================================================
//STEP01   EXEC PGM=CRECUST
//STEPLIB  DD DSN=HERC01.LOADLIB,DISP=SHR
//SYSOUT   DD SYSOUT=*
//SYSPRINT DD SYSOUT=*
//SYSUDUMP DD SYSOUT=*
//