import re
import math
from collections import Counter

class SecurityLens:
    """
    The GitGalaxy Physics Engine for Threat Detection.
    Measures raw structural realities (Regex Hits & Shannon Entropy) and compares them 
    against dynamically injected Policy Thresholds.
    """
    
    def __init__(self, policy=None):
        # ------------------------------------------------------------------
        # DYNAMIC POLICY INJECTION
        # ------------------------------------------------------------------
        self.policy = policy or {
            "secrets_risk_threshold": 0.001,
            "hidden_malware_threshold": 0.60,
            "logic_bomb_threshold": 0.50,
            "injection_surface_threshold": 0.65,
            "memory_corruption_threshold": 0.60
        }

        # Regex to quickly capture strings wrapped in single or double quotes for Entropy math
        self.string_extractor = re.compile(r'(["\'])(.*?)\1')
        
        # ---> THE AUTO-GEN SHIELD <---
        self.auto_gen_shield = re.compile(r'(?:/\*\s*eslint-disable\s*\*/|@generated|DO NOT EDIT|Auto-generated by|generated by swagger|machine generated)', re.I)

        # ---> THE X-RAY BINARY SENSOR CONSTANTS <---
        self.MAGIC_BYTES = {
            ".png": b"\x89PNG\r\n\x1a\n",
            ".jpg": b"\xff\xd8\xff",
            ".jpeg": b"\xff\xd8\xff",
            ".xz": b"\xfd7zXZ\x00",
            ".gz": b"\x1f\x8b",
            ".pdf": b"%PDF-",
            ".zip": b"PK\x03\x04"
        }
        
        self.THREAT_HEADERS = [
            b"\x7fELF",        # Linux Executable
            b"MZ",             # Windows Executable
            b"#!/bin/",        # Shell Script
            b"\x00asm",        # WebAssembly
            b"\xCF\xFA\xED\xFE" # macOS Mach-O
        ]

        # ------------------------------------------------------------------
        # RAW SENSORS (The Physics Engine)
        # ------------------------------------------------------------------
        self.THREAT_SIGNATURES = {
            # 1. THE GLASSWORM (Obfuscation & Heat Signatures)
            "heat_triggers": re.compile(
                r'\b(?:atob|btoa|base64_decode|base64_encode|gzuncompress|str_rot13)\b|'
                r'\\x[0-9a-fA-F]{2}|\\u[0-9a-fA-F]{4}|'
                r'(?:\w{15,}[ \t]*=[ \t]*["\'][A-Za-z0-9+/]{40,}={0,2}["\'])|'
                r'[\u200B-\u200D\uFEFF\u200E\u200F\u202A-\u202E]', # Invisible Unicode
                re.I
            ),

            # 2. THE TROJAN (Identity Masking & Safety Bypasses)
            "safety_neg": re.compile(
                r'\b(?:atob|btoa|base64_decode|gzinflate|gzuncompress|str_rot13|urldecode)[ \t]*\([ \t]*(?:atob|btoa|base64_decode|gzinflate|gzuncompress|str_rot13|urldecode)\b|'
                r'\b(?:auto_prepend_file|auto_append_file)\b|'
                r'\b(?:ini_set|ini_restore|putenv)[ \t]*\([ \t]*["\'](?:disable_functions|safe_mode|open_basedir|allow_url_fopen)["\'][ \t]*,[ \t]*["\']?(?:0|off|false|)["\']?\)|'
                r'\b(?:disable_functions|safe_mode|open_basedir)\b[ \t]*=[ \t]*(?:off|0|false|""|\'\')|'
                r'process\.env\.NODE_TLS_REJECT_UNAUTHORIZED[ \t]*=[ \t]*["\']?0["\']?|'
                r'\b(?:verify|strictSSL|rejectUnauthorized|CURLOPT_SSL_VERIFYPEER)[ \t]*[=:,][ \t]*(?:False|false|0)\b',
                re.I
            ),

            # 3. EXFILTRATION VECTORS (System Gravity)
            "io": re.compile(
                r'\b(?:fetch|XMLHttpRequest|WebSocket|http\.request|https\.request|requests\.(?:post|put|get)|urllib\.request\.urlopen)\b\s*\(|'
                r'\b(?:curl_exec|fsockopen|pfsockopen|stream_socket_client|file_get_contents)\b\s*\(|'
                r'\b(?:dns_get_record|gethostbyname|socket\.gethostbyname|resolve(?:4|6|Cname|Txt)?)\b\s*\(|'
                r'(?:https?|ftp|tcp|udp|wss?):\/\/(?:(?:\d{1,3}\.){3}\d{1,3}|\[[0-9a-fA-F:]+\]|.*?\.(?:ngrok\.io|ngrok-free\.app|localtunnel\.me|pastebin\.com|workers\.dev|s3\.amazonaws\.com|requestbin\.net|pipedream\.net))',
                re.I | re.X
            ),

            # 4. THE EXECUTIONER (Dynamic Payloads & Context Injections)
            "danger": re.compile(
                r'\b(?:BPXBATCH|IKJEFT01|IRXJCL)\b|'
                r'\bEXEC\s+CICS\s+(?:START|LINK\s+PROGRAM|XCTL)\b\s*\(\s*[A-Za-z_-]+\s*\)|'
                r'\b(?:eval|Function|setTimeout|setInterval)\b\s*\(\s*(?:atob|base64_decode|gzinflate|\$|_[a-zA-Z]|["\']|`)|'
                r'\b(?:document\.write|location\.replace|assert|create_function|passthru|shell_exec|system)\b|'
                r'child_process\.(?:exec|spawn|fork)|'
                r'(?:window|global|this|globalThis)\[[ \t]*(?:["\'][a-zA-Z]["\'][ \t]*\+[ \t]*){1,15}["\'][a-zA-Z]["\'][ \t]*\][ \t]*\(|'
                r'\$[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*\s*\(\s*\$_(?:POST|GET|COOKIE|REQUEST|HEADERS)|'
                r'getattr\s*\(\s*__import__\s*\(|__builtins__\[|Assembly\.Load\s*\(|'
                r'\$\{\{\s*github\.event\.(?:issue|pull_request|comment|review|push\.commits).*?\}\}', # <--- NEW: CI/CD Untrusted Context Injection
                re.I | re.X
            ),

            # 5. ENVIRONMENT POISONING (State Flux)
            "flux": re.compile(
                r'\b[A-Za-z0-9_]+\.prototype\.[A-Za-z0-9_]+[ \t]*=|'
                r'\.__proto__[ \t]*=[ \t]*[{a-zA-Z]|'
                r'\b(?:window|global|globalThis|document)\.(?:fetch|eval|setTimeout|setInterval|Promise|console|JSON)[ \t]*=|'
                r'\$(?:GLOBALS|_(?:SERVER|GET|POST|COOKIE|REQUEST|ENV|SESSION))\[[^\]]+\][ \t]*=[ \t]*[^=]|'
                r'\bextract[ \t]*\([ \t]*\$(?:_(?:GET|POST|REQUEST|COOKIE)|GLOBALS)\b|'
                r'\b__builtins__\[[^\]]+\][ \t]*=|'
                r'\bsys\.modules\[[^\]]+\][ \t]*=',
                re.I
            ),

            # 6. SHADOW LOGIC (Necrosis / Graveyard)
            "graveyard": re.compile(
                r'(?://|#|--|\*>|^.{6}\*)[^\n]*?\b(?:http|bash|curl|wget|eval|base64|nc\s+-e|/dev/tcp|BPXBATCH)\b|'
                r'/\*(?:(?!\*/).){0,500}?\b(?:http|bash|curl|wget|eval|base64|nc\s+-e|/dev/tcp)\b',
                re.I
            ),
            
            # 7. SUB-ATOMIC DECRYPTION (Bitwise Hits)
            "bitwise_hits": re.compile(
                r'\b\w+[ \t]*=[ \t]*(?:\w+[ \t]*\^[ \t]*\w+[ \t]*){2,20}|'
                r'(?:\w+\[[^\]\n]{1,50}\][ \t]*\^[ \t]*=?[ \t]*(?:0x[0-9a-fA-F]+|\d+|\w+)[ \t]*;[ \t]*){3,20}', 
                re.I
            ),
            
            # 8. SHADOW IMPORTS (The Switcharoo / Steganography)
            "shadow_imports": re.compile(
                r'\b(?:require|include|import|require_once|include_once|source|load|dofile)\b\s*\(?\s*'
                r'["\'][^"\']+\.(?:png|jpg|jpeg|gif|ico|pdf|zip|tar|dat|tmp|log|txt|csv|wav|mp3)["\']',
                re.I
            ),
            
            # 9. UNICODE SMUGGLING (Homoglyphs & Typosquatting)
            "homoglyphs": re.compile(
                r'\b(?:import|from|require|include|require_once|fetch|XMLHttpRequest)\b'
                r'[^\n]*?(?:[\u0400-\u04FF]|'       
                r'[\u0370-\u03FF]|'                 
                r'[\u1D400-\u1D7FF]|'               
                r'\u3164)',                         
                re.I
            ), 
            
            # 10. THE VAULT DOOR (Credential & Secret Leaks)
            "private_info": re.compile(
                r"\b(password|secret|token|api[_-]?key|client[_-]?secret|credentials|private[_-]?key|auth[_-]?token)\b[ \t]*(?:[:=]|=>)[ \t]*[\"'][A-Za-z0-9\-_+/=]{16,}[\"']|"
                r"\b(PASSWORD|SECRET|TOKEN|KEY|CREDENTIALS)[A-Za-z0-9_-]*\b[ \t]+(?:IS[ \t]+)?(?:PIC[ \t]+[A-Za-z0-9\-\(\)]+[ \t]+)?VALUE[ \t]+['\"][^'\"]+['\"]|"
                r"-----BEGIN (?:RSA |DSA |EC |OPENSSH |PGP )?(?:PRIVATE KEY|MESSAGE|CERTIFICATE)-----|"
                r"\b(?:sk_live|rk_live)_[0-9a-zA-Z]{24,99}\b|"
                r"\bghp_[0-9a-zA-Z]{36}\b|"
                r"\bxox[baprs]-[0-9a-zA-Z]{10,48}\b|"
                r"\bAIza[0-9A-Za-z\-_]{35}\b|"
                r"\b(?:AKIA|ABIA|ACCA|ASIA)[0-9A-Z]{16}\b|"
                r"ssh-(?:rsa|ed25519)[ \t]+[A-Za-z0-9+/]+[=]{0,2}",
                re.I
            ),
            
            # 11. RAW MEMORY OVERRIDES 
            "memory_corruption": re.compile(
                r'\bEXEC\s+CICS\s+(?:GETMAIN|FREEMAIN)\b|'
                r'\bSET\s+ADDRESS\s+OF\b|'
                r'\b(?:malloc|calloc|realloc|free|memcpy|memset|memmove|strcpy|strcat|sprintf)\b\s*\(|'
                r'\b(?:asm|__asm__|__asm)\b\s*[\(\{]',
                re.I
            )
        }

    def _calculate_shannon_entropy(self, data: str) -> float:
        """Calculates the Shannon Entropy of a string. Extremely fast via C-backed Counter."""
        if not data:
            return 0.0
            
        entropy = 0.0
        length = len(data)
        frequencies = Counter(data)
        
        for count in frequencies.values():
            probability = count / length
            entropy -= probability * math.log2(probability)
            
        return entropy

    def scan_content(self, content: str, loc: int) -> dict:
        counts = {}
        snippets = {}
        
        # ---> THE MINIFICATION SHIELD <---
        # Only extract snippets from human-readable lines (under 250 chars)
        safe_lines = [line.strip() for line in content.splitlines() if len(line) < 250]
        safe_content = "\n".join(safe_lines)

        # ---> THE AUTO-GEN SHIELD <---
        # If a file is machine-generated, it naturally contains massive string blocks and ugly escapes.
        # We check the first 2000 characters to see if it announces itself as auto-generated.
        is_auto_gen = bool(self.auto_gen_shield.search(content[:2000]))

        for key, regex in self.THREAT_SIGNATURES.items():
            # If auto-generated, skip homoglyph Evasion checks to prevent false positives
            if is_auto_gen and key == "homoglyphs":
                counts[key] = 0
                snippets[key] = []
                continue
                
            # 1. Count the raw hits for the X-Ray (even in minified code)
            counts[key] = len(regex.findall(content))
            
            # 2. Extract the Smoking Gun snippets
            snippets[key] = []
            if counts[key] > 0:
                for match in regex.finditer(safe_content):
                    snip = match.group(0).strip()
                    if snip not in snippets[key]:
                        snippets[key].append(snip)
                    # Cap at top 3 unique hits per vector to prevent log flooding
                    if len(snippets[key]) >= 3: 
                        break

        # ---> 3. SHANNON ENTROPY (The Math of Chaos) <---
        entropy_hits = 0
        entropy_snippets = []
        
        # If the file is auto-generated, skip entropy math entirely
        if is_auto_gen:
            counts["entropy"] = 0
            snippets["entropy"] = []
            return {"counts": counts, "snippets": snippets}
            
        for match in self.string_extractor.finditer(safe_content):
            extracted_string = match.group(2)
            # THE SHIELDS: Only run math on strings that are long and dense
            if len(extracted_string) > 64 and extracted_string.count(" ") < 3:
                entropy = self._calculate_shannon_entropy(extracted_string)
                # The Threshold: > 4.8 indicates highly packed/encrypted payloads
                if entropy > 4.8:
                    entropy_hits += 1
                    if len(entropy_snippets) < 3:
                        entropy_snippets.append(extracted_string[:60] + "...") 
                        
        counts["entropy"] = entropy_hits
        snippets["entropy"] = entropy_snippets
                        
        # ---> 4. LIGHTWEIGHT TAINT ANALYSIS (Universal LHS Slicer) <---
        taint_hits = 0
        taint_snippets = []
        
        # O(1) Short-Circuit: Taint is impossible if there's no I/O or no execution
        if counts.get("io", 0) > 0 and counts.get("danger", 0) > 0 and not is_auto_gen:
            tainted_vars = set()
            # Common language keywords to ignore during variable extraction
            common_keywords = {"const", "let", "var", "def", "String", "int", "val", "final", "char", "bool", "auto", "global", "local"}
            
            for line in safe_lines:
                has_io = bool(self.THREAT_SIGNATURES["io"].search(line))
                has_danger = bool(self.THREAT_SIGNATURES["danger"].search(line))
                
                # Scenario A: Same-Line Detonation (e.g. eval($_POST['data']))
                if has_io and has_danger:
                    taint_hits += 1
                    if len(taint_snippets) < 3: taint_snippets.append(line[:60] + "...")
                    continue
                    
                # Scenario B: The LHS Slicer (Capture Input)
                if has_io:
                    assign_op = ":=" if ":=" in line else "=" if "=" in line else None
                    if assign_op:
                        lhs = line.split(assign_op)[0]
                        # Extract potential variable names (handles destructuring naturally)
                        possible_vars = re.findall(r'\b[a-zA-Z_]\w*\b', lhs)
                        for v in possible_vars:
                            if v not in common_keywords:
                                tainted_vars.add(v)
                                
                # Scenario C: The Downward Scan (Check Execution)
                if has_danger and tainted_vars:
                    # Did a tainted variable touch this danger line?
                    for t_var in tainted_vars:
                        # Use word boundaries so 'id' doesn't flag 'hidden'
                        if re.search(rf'\b{re.escape(t_var)}\b', line):
                            taint_hits += 1
                            if len(taint_snippets) < 3: taint_snippets.append(line[:60] + "...")
                            break # Count the line once and move on

        counts["tainted_injection"] = taint_hits
        snippets["tainted_injection"] = taint_snippets
        
        # Return a nested dictionary
        return {"counts": counts, "snippets": snippets}

    def evaluate_risk(self, aggregated_hits, total_loc):
        """
        Takes the raw physics hits, calculates the density, and checks 
        if it breaches the dynamically injected policy thresholds.
        """
        # Prevent division by zero
        loc_safe = total_loc if total_loc > 0 else 1
        
        exposures = {}
        
        # 1. Hidden Malware Risk
        malware_hits = aggregated_hits.get("heat_triggers", 0) + aggregated_hits.get("bitwise_hits", 0) + aggregated_hits.get("shadow_imports", 0) + aggregated_hits.get("homoglyphs", 0) + aggregated_hits.get("entropy", 0)
        malware_density = malware_hits / loc_safe
        if malware_density >= self.policy["hidden_malware_threshold"]:
            exposures["Hidden Malware Risk"] = malware_density

        # 2. Logic Bomb / Sabotage Risk
        sabotage_hits = aggregated_hits.get("graveyard", 0) + (aggregated_hits.get("danger", 0) * 1.5)
        sabotage_density = sabotage_hits / loc_safe
        if sabotage_density >= self.policy["logic_bomb_threshold"]:
            exposures["Logic Bomb Risk"] = sabotage_density

        # 3. Data Injection Risk
        injection_hits = aggregated_hits.get("io", 0) + aggregated_hits.get("danger", 0) + aggregated_hits.get("flux", 0)
        injection_density = injection_hits / loc_safe
        if injection_density >= self.policy["injection_surface_threshold"]:
            exposures["Data Injection Risk"] = injection_density

        # 4. Memory Corruption Risk
        memory_hits = aggregated_hits.get("memory_corruption", 0)
        memory_density = memory_hits / loc_safe
        if memory_density >= self.policy["memory_corruption_threshold"]:
            exposures["Memory Corruption Risk"] = memory_density

        # 5. Secrets Risk
        secrets_hits = aggregated_hits.get("private_info", 0)
        secrets_density = secrets_hits / loc_safe
        if secrets_density >= self.policy["secrets_risk_threshold"]:
            exposures["Secrets Leak Risk"] = secrets_density

        return exposures

    def scan_binary(self, raw_bytes: bytes, ext: str) -> dict:
        """
        X-Rays binary chunks for embedded execution headers, magic byte mismatches, 
        and extreme cryptographic entropy.
        """
        threats = {}
        
        if not raw_bytes:
            return threats

        # 1. Magic Byte Verification (Mismatch)
        expected_magic = self.MAGIC_BYTES.get(ext.lower())
        if expected_magic:
            if not raw_bytes.startswith(expected_magic):
                threats["sec_extension_mismatch"] = 1
                threats["threat_snippet"] = f"Expected {expected_magic}, found mismatch"

        # 2. Embedded Execution Headers (Parasite)
        for header in self.THREAT_HEADERS:
            # We search the whole chunk, not just the start, to catch appended payloads
            if header in raw_bytes:
                threats["sec_danger"] = 1
                threats["threat_snippet"] = f"Embedded execution header found: {header}"
                break

        # 3. High-Entropy Carving
        try:
            length = len(raw_bytes)
            if length > 256:
                frequencies = Counter(raw_bytes)
                entropy = 0.0
                for count in frequencies.values():
                    probability = count / length
                    entropy -= probability * math.log2(probability)
                
                # Uncompressed text/bitmaps usually hover around 4-5. 
                # Encrypted/Heavily packed payloads push 7.9+
                if entropy > 7.95:
                    threats["sec_heat_triggers"] = 1
                    threats["threat_snippet"] = f"Extreme binary entropy detected: {entropy:.2f}"
        except Exception:
            pass

        return threats