# ==============================================================================
# GitGalaxy
# Copyright (c) 2026 Joe Esquibel
#
# This source code is licensed under the PolyForm Noncommercial License 1.0.0.
# You may not use this file except in compliance with the License.
# A copy of the license can be found in the LICENSE file in the root directory
# of this project, or at [https://polyformproject.org/licenses/noncommercial/1.0.0/](https://polyformproject.org/licenses/noncommercial/1.0.0/)
# ==============================================================================
import os
import logging
import fnmatch
import re
from pathlib import Path
from typing import Dict, Any, Set, Optional, TypedDict, Union, List, Tuple

# ==============================================================================
# GitGalaxy Phase 0.1: Ingestion & Filtering (The Aperture Filter)
# Strategy: v6.3.1 (Monolith Ceilings, Array Shields & Intent Overrides)
# Architecture: Path Evaluation -> Intent Resolution -> Content Validation
# ==============================================================================

# --- CUSTOM EXCEPTION HIERARCHY ---

class ApertureError(Exception):
    """Base class for all errors generated by the Aperture filtering process."""
    pass

class InaccessibleArtifactError(ApertureError):
    """Raised when an artifact cannot be accessed due to OS permissions or path corruption."""
    pass

class SaturationError(ApertureError):
    """Raised when a signal is too dense or minified to be safely evaluated by the engine."""
    pass


class FilterResult(TypedDict):
    """Structured telemetry returned by the Filter for the Pipeline Orchestrator."""
    is_in_scope: bool
    classification: str  # e.g., 'source_code', 'binary_payload', 'generated_noise'
    reason: Optional[str]
    path: str
    size_bytes: int
    total_loc: int


class ApertureFilter:
    """
    Primary ingestion filter for the analysis engine. Performs perimeter gating to ensure
    only valid, maintainable source code reaches the CPU-bound Regex/AST detectors. 
    Integrates with GuideStar's Bayesian 'Intent Locks' to dynamically adjust suppression
    thresholds for known, high-priority artifacts (like package.json).
    """

    def __init__(
        self,
        root_dir: Union[str, Path],
        language_definitions: Dict[str, Any],
        aperture_config: Dict[str, Any],
        parent_logger: Optional[logging.Logger] = None,
    ):
        # --- TELEMETRY SYNC ---
        if parent_logger:
            self.logger = parent_logger.getChild("filter")
            self.logger.setLevel(parent_logger.level)
        else:
            self.logger = logging.getLogger("filter")
            self.logger.setLevel(logging.INFO)

        self.root = Path(root_dir).resolve()
        self.registry = language_definitions
        self.config = aperture_config or {}

        self.ignored_directories = set(self.config.get("BLACK_HOLES", set()))
        self.ignored_extensions = set(self.config.get("BLACK_HOLE_EXTENSIONS", set()))
        self.denylist_patterns = self.config.get("CONTRABAND_PATTERNS", [])

        # ---> AUTO-GENERATED DOC SHIELD <---
        # DEFENSIVE DESIGN: Parsers waste massive compute on Doxygen/Sphinx HTML dumps.
        # This regex identifies the exact generator signatures.
        self.doc_generator_pattern = re.compile(
            r'<meta\s+name=["\']generator["\']\s+content=["\'](?:jazzy|Doxygen|Sphinx|JSDoc|TypeDoc|appledoc|Docco|MkDocs|Hugo|DocFX|Docgen).*?["\']'
        )

        # ---> MACHINE-GENERATED SOURCE SHIELD <---
        # Identifies source code generated by external transpilers or ORMs.
        self.machine_gen_pattern = re.compile(
            r"(?i)(?:<auto-generated>|\bdo not edit\b|auto-generated|automatically generated|this file is generated|generated by \S+)"
        )

        # ---> SEMANTIC PATH SHIELD <---
        # Matches boundaries commonly associated with generated, build, vendor, and noise directories.
        self.infra_path_pattern = re.compile(
            r"(?i)[-_./\\]?(?:gen|generated|build|dist|out|vendor|mock|test|spec|docs|assets|scripts|__monolith__|__snapshots__|.github|.gitlab|node_modules|third[-_]?party|deps?|lib(?:rary|raries)?)[-_./\\]?\b"
        )

        # --- STATE CACHE & DYNAMIC STATE ---
        self._intent_cache: Set[str] = set()
        self.dynamic_ignore_dirs: Set[str] = set()

        self.logger.debug(f"Initializing Aperture Filter for project: '{self.root.name}'...")

        # Optimized Lookup Construction
        self.whitelisted_extensions: Set[str] = set()
        self.exact_match_files: Set[str] = set()

        for lang_id, data in self.registry.items():
            self.whitelisted_extensions.update(data.get("extensions", []))
            self.exact_match_files.update(data.get("exact_matches", []))

        self.ignore_patterns = self._load_gitignore_patterns()

        self.logger.info(
            f"Aperture Filter Online | "
            f"Tracking {len(self.whitelisted_extensions)} valid extensions."
        )

    def evaluate_path_integrity(
        self, file_path: Union[str, Path], has_intent: bool = False
    ) -> Tuple[bool, int, str]:
        """
        [PHASE 0 ENTRY POINT]
        Performs high-speed path analysis to build the initial File Census.
        
        DEFENSIVE DESIGN: We determine if a file is physically valid based on OS metadata
        *before* any disk I/O (file opening/reading) occurs. This prevents OS-level locks 
        and drastically reduces Memory/CPU overhead on large monolithic repositories.
        """
        path_obj = Path(file_path)
        normalized_path = path_obj.as_posix()
        _, ext = os.path.splitext(path_obj.name)

        try:
            relative_path = path_obj.relative_to(self.root).as_posix()
        except ValueError:
            relative_path = normalized_path

        try:
            size_bytes = path_obj.stat().st_size if path_obj.exists() else 0
        except OSError:
            size_bytes = 0

        # --- TIER 0.1: THE SECRETS RADAR ---
        if path_obj.name in self.config.get(
            "SECRETS_EXACT", set()
        ) or ext.lower() in self.config.get("SECRETS_EXTENSIONS", set()):
            reason = f"CRITICAL LEAK (Exposed Secret: '{path_obj.name}')"
            return False, size_bytes, reason

        # --- TIER 0.2: THE NEURAL AUDITOR SHUNT (Model Weights) ---
        AI_MODEL_EXTS = {
            ".safetensors", ".gguf", ".onnx", ".pt", ".pth", 
            ".bin", ".tflite", ".pb", ".h5",
        }
        if ext.lower() in AI_MODEL_EXTS:
            reason = f"AI MODEL WEIGHTS (Bypassing Standard Logic: '{ext}')"
            self.logger.info(f"NEURAL SHUNT: Routing {path_obj.name} away from standard regex engines.")
            return False, size_bytes, reason

        # --- TIER 0.5: THE ABSOLUTE EXTENSION SHIELD ---
        if ext.lower() in self.ignored_extensions and ext.lower() not in self.whitelisted_extensions:
            reason = f"Blocked (Explicitly Denied Extension: '{ext}')"
            return False, size_bytes, reason

        # Establish Intent Lock
        active_intent = has_intent or (normalized_path in self._intent_cache)
        if active_intent:
            self._intent_cache.add(normalized_path)

# --- TIER 1: CHECK EXPLICIT IGNORE RULES (.gitignore, node_modules, etc) ---
        if not self._check_ignore_rules(relative_path, has_intent=active_intent):
            reason = "Blocked (System Exclusion, Hidden Directory, or Dynamic Ignored Dir)"
            return False, size_bytes, reason

        # --- TIER 2: VALIDATE AGAINST SUPPORTED REGISTRY ---
        if active_intent:
            return True, size_bytes, "Passed (GuideStar Intent Lock)"

        if not ext:
            return True, size_bytes, "Passed (Extensionless -> Subject to Shebang scan)"

        if path_obj.name in self.exact_match_files or ext.lower() in self.whitelisted_extensions:
            return True, size_bytes, "Passed (Whitelisted)"

        reason = f"Blocked (Unsupported Extension: '{ext}')"
        return False, size_bytes, reason

    def is_in_scope(
        self,
        file_path: Union[str, Path],
        content: Optional[str] = None,
        has_intent: bool = False,
    ) -> FilterResult:
        """
        [PHASE 1 ENTRY POINT]
        The final Content Gate. Validates the physical matter of the artifact
        to ensure it is not binary, minified, or auto-generated debris.
        """
        path_obj = Path(file_path)
        normalized_path = path_obj.as_posix()
        relative_path = (
            str(path_obj.relative_to(self.root))
            if path_obj.is_relative_to(self.root)
            else normalized_path
        )
        active_intent = has_intent or (normalized_path in self._intent_cache)

        result: FilterResult = {
            "is_in_scope": False,
            "classification": "source_code",
            "reason": None,
            "path": normalized_path,
            "size_bytes": 0,
            "total_loc": 0,
        }

        try:
            if not path_obj.exists():
                raise InaccessibleArtifactError("Artifact missing on disk")

            stats = path_obj.stat()
            result["size_bytes"] = stats.st_size

            # --- TIER 0: RESOURCE GUARDING (Hard Limits) ---
            # DEFENSIVE DESIGN: A hard 10MB limit prevents a single massive log or SQL dump
            # from consuming all available RAM and triggering an OOM kill from the OS.
            max_mb = self.config.get("MAX_FILE_SIZE_MB", 10)
            if stats.st_size > (max_mb * 1024 * 1024):
                result.update(
                    {
                        "classification": "oversized_minified",
                        "reason": f"Blocked (File size exceeds {max_mb}MB limit)",
                    }
                )
                return result

            # --- TIER 1 & 2: PATH VALIDATION ---
            is_valid, size_bytes, reason = self.evaluate_path_integrity(path_obj, has_intent=active_intent)

            if not is_valid:
                result.update({"classification": "generated_noise", "reason": reason})
                return result

            # --- THE SHUNT: SECRETS BYPASS ---
            if reason and "CRITICAL LEAK" in reason:
                result.update(
                    {
                        "is_in_scope": True,
                        "classification": "source_code",
                        "reason": reason,
                        "total_loc": len(content.splitlines()) if content else 0,
                    }
                )
                return result

            # --- TIER 3 & 4: CONTENT VALIDATION ---
            if content is None:
                result["reason"] = "Protocol Violation: Missing content buffer"
                return result

            integrity = self._check_artifact_integrity(
                content, relative_path, has_intent=active_intent
            )
            result["total_loc"] = integrity["loc"]

            if not integrity["valid"]:
                result.update({"classification": integrity["classification"], "reason": integrity["reason"]})
                return result

            # --- MISSION SUCCESS ---
            result["is_in_scope"] = True
            return result

        except Exception as e:
            self.logger.error(f"Filter Collision on '{relative_path}': {str(e)}")
            result["reason"] = f"Internal Exception: {str(e)}"
            return result

    def _check_artifact_integrity(
        self, content: str, rel_path: str, has_intent: bool = False
    ) -> Dict[str, Any]:
        """
        Deep-scans the content buffer for corruption, binary data, arrays,
        or documentation generator signatures.
        """
        report = {
            "valid": True,
            "classification": "source_code",
            "reason": None,
            "loc": 0,
        }

        # Split lines early so we can use LOC for all heuristics
        lines_list = content.splitlines()
        report["loc"] = len(lines_list)

        # --- TIER 3: OPAQUE BINARY DETECTION ---
        # DEFENSIVE DESIGN: Checking for a null byte is the fastest, most reliable 
        # heuristic to identify compiled binaries or images masquerading as text files.
        if "\x00" in content:
            report.update(
                {
                    "valid": False,
                    "classification": "binary_payload",
                    "reason": "Blocked (Binary Format Detected)",
                }
            )
            return report

        # --- TIER 3.1: THE MONOLITH AMALGAMATION SHIELD ---
        # DEFENSIVE DESIGN: 30,000+ lines in a single file is usually an amalgamation (e.g. sqlite3.c).
        # Standard Regex engines suffer from Catastrophic Backtracking on files of this magnitude.
        if report["loc"] > 30000:
            report.update(
                {
                    "valid": False,
                    "classification": "oversized_minified",
                    "reason": f"Blocked (Monolithic Amalgamation: {report['loc']} LOC exceeds safe regex boundaries)",
                }
            )
            return report

        # --- TIER 3.5: AUTO-GEN DOC SHIELD ---
        low_path = rel_path.lower()
        if low_path.endswith((".html", ".htm", ".xml")):
            head_sample = "\n".join(lines_list[:100])
            if self.doc_generator_pattern.search(head_sample):
                parent_dir = str(Path(rel_path).parent)
                if parent_dir != ".":
                    self.dynamic_ignore_dirs.add(parent_dir)
                    self.logger.debug(f"Dynamic Ignore: Directory '{parent_dir}' flagged as Auto-Generated Docs.")

                report.update(
                    {
                        "valid": False,
                        "classification": "generated_noise",
                        "reason": "Blocked (Machine-Generated Documentation Signature)",
                    }
                )
                return report

        # --- TIER 3.6: MACHINE-GENERATED SOURCE SHIELD ---
        head_sample = "\n".join(lines_list[:100])
        if self.machine_gen_pattern.search(head_sample):
            if not has_intent or report["loc"] > 1000:
                report.update(
                    {
                        "valid": False,
                        "classification": "generated_noise",
                        "reason": f"Blocked (Machine-Generated Source Code Signature: {report['loc']} LOC)",
                    }
                )
                return report

        # --- TIER 3.7: LEXICAL MONOTONY SHIELD (Generated Code) ---
        if report["loc"] > 2000 and not has_intent and not low_path.endswith((".cpy", ".cbl", ".cob")):
            sample_lines = lines_list[:500]
            meaningful_lines = [l for l in sample_lines if l.strip()]

            if len(meaningful_lines) > 100:
                indent_counts = {}
                for l in meaningful_lines:
                    indent = len(l) - len(l.lstrip())
                    indent_counts[indent] = indent_counts.get(indent, 0) + 1

                max_indent_freq = max(indent_counts.values())
                if (max_indent_freq / len(meaningful_lines)) > 0.85:
                    report.update(
                        {
                            "valid": False,
                            "classification": "generated_noise",
                            "reason": f"Blocked (Lexical Monotony: High structural repetition detected in {report['loc']} LOC)",
                        }
                    )
                    return report

        # --- TIER 3.8: DECLARATIVE & VECTOR DATA SHIELD ---
        if low_path.endswith((".yml", ".yaml", ".json", ".xml", ".svg", ".sql", ".csv", ".tsv")):
            if report["loc"] > 2500:
                report.update(
                    {
                        "valid": False,
                        "classification": "generated_noise",
                        "reason": f"Blocked (Massive Declarative/Vector Blob: {report['loc']} LOC)",
                    }
                )
                return report
            elif not has_intent and report["loc"] > 1000:
                report.update(
                    {
                        "valid": False,
                        "classification": "generated_noise",
                        "reason": f"Blocked (Declarative Data Blob without Intent: {report['loc']} LOC)",
                    }
                )
                return report

        # --- TIER 3.9: TEST DATA & ARRAY SHIELD ---
        # DEFENSIVE DESIGN: Massive comma-separated arrays or hex blobs (like embedded images
        # inside C++ headers) contain 0 architectural logic, but will completely stall an AST parser.
        if report["loc"] > 500:
            hex_count = content.count("0x") + content.count("0X")
            if hex_count > report["loc"]:
                report.update(
                    {
                        "valid": False,
                        "classification": "binary_payload",
                        "reason": f"Blocked (Embedded Hex Payload: {hex_count} hex tokens in {report['loc']} LOC)",
                    }
                )
                return report

            comma_count = content.count(",")
            if comma_count > (report["loc"] * 3):
                report.update(
                    {
                        "valid": False,
                        "classification": "binary_payload",
                        "reason": f"Blocked (Embedded Array/Matrix Payload: {comma_count} commas in {report['loc']} LOC)",
                    }
                )
                return report

        # --- TIER 4: MINIFICATION & SATURATION GATE ---
        max_line = self.config.get("MAX_LINE_LENGTH", 500)
        is_prose = low_path.endswith((".md", ".markdown", ".txt", ".json", ".csv", ".rst", ".sql", ".svg"))

        for i, line in enumerate(lines_list[:100]):
            if len(line) > max_line and not is_prose:
                report.update(
                    {
                        "valid": False,
                        "classification": "oversized_minified",
                        "reason": f"Blocked (Saturation: Line {i+1} exceeds {max_line} chars)",
                    }
                )
                return report

        return report

    def _check_ignore_rules(self, rel_path: str, has_intent: bool = False) -> bool:
        """
        Determines if the path is in a blocked, ignored, or dynamically
        infected sector. Implements standard .gitignore functionality alongside
        hardcoded vendor/infrastructure exclusions.
        """
        parts = rel_path.split("/")

        # 1. Static Ignored Directories & Hidden Paths
        for part in parts:
            low_part = part.lower()
            if low_part in self.ignored_directories:
                return False

            if part.startswith(".") and part not in self.exact_match_files:
                if not has_intent:
                    return False

        # 2. Dynamic Documentation Debris Shield
        path_obj = Path(rel_path)
        for parent in path_obj.parents:
            if str(parent) in self.dynamic_ignore_dirs:
                self.logger.debug(f"Dynamic Deflection: Asset '{rel_path}' blocked in auto-generated directory.")
                return False

        # 3. Semantic Infrastructure & Test Target Shield
        if self.infra_path_pattern.search(rel_path):
            if not has_intent:
                return False

        # 4. The Denylist (Vendor Blob Deflection)
        filename = parts[-1]
        for pattern in self.denylist_patterns:
            if fnmatch.fnmatch(filename, pattern):
                return False

        # 5. Standard Iterative .gitignore Logic
        for pattern in self.ignore_patterns:
            if pattern.endswith("/"):
                if any(fnmatch.fnmatch(p + "/", pattern) for p in parts):
                    return False
            else:
                if fnmatch.fnmatch(rel_path, pattern) or fnmatch.fnmatch(
                    filename, pattern
                ):
                    return False

        return True

    def _load_gitignore_patterns(self) -> List[str]:
        """Reads local .gitignore files to identify un-tracked noise."""
        patterns = []
        ignore_file = self.root / ".gitignore"

        if ignore_file.exists():
            try:
                with ignore_file.open("r", encoding="utf-8") as f:
                    for line in f:
                        clean_line = line.strip()
                        if clean_line and not clean_line.startswith("#"):
                            patterns.append(clean_line)
            except Exception as e:
                self.logger.warning(f"Failed to parse .gitignore: {e}")

        return patterns