# ==============================================================================
# GitGalaxy
# Copyright (c) 2026 Joe Esquibel
#
# This source code is licensed under the PolyForm Noncommercial License 1.0.0.
# You may not use this file except in compliance with the License.
# A copy of the license can be found in the LICENSE file in the root directory
# of this project, or at https://polyformproject.org/licenses/noncommercial/1.0.0/
# ==============================================================================
import os
import logging
import fnmatch
import re
from pathlib import Path
from typing import Dict, Any, Set, Optional, TypedDict, Union, List, Tuple

# ==============================================================================
# GitGalaxy Phase 0.1: Ingestion & Filtering (The Solar Shield)
# Strategy: v6.3.1 (Monolith Ceilings, Array Shields & Intent Overrides)
# Architecture: Lead Shield -> Path Gate -> Intent Gate -> Content Gate
# ==============================================================================

# --- CUSTOM EXCEPTION HIERARCHY (The Lead Shield) ---


class ApertureError(Exception):
    """Base class for all errors generated by the Solar Shield filtering process."""

    pass


class InaccessibleArtifactError(ApertureError):
    """Raised when an artifact cannot be accessed due to OS permissions or path corruption."""

    pass


class SaturationError(ApertureError):
    """Raised when a signal is too dense or minified to be safely refracted by the detector."""

    pass


class FilterResult(TypedDict):
    """Structured telemetry returned by the Solar Shield for the Pipeline Orchestrator."""

    is_in_scope: bool
    band: str
    reason: Optional[str]
    path: str
    size_bytes: int
    total_loc: int


class ApertureFilter:
    """
    Primary solar shield for the telescope. Performs perimeter gating to ensure
    only maintainable source code matter reaches the detector. Integrates with
    GuideStar's Bayesian 'Intent Locks' to dynamically adjust suppression
    thresholds for known, high-priority artifacts.
    """

    def __init__(
        self,
        root_dir: Union[str, Path],
        language_definitions: Dict[str, Any],
        aperture_config: Dict[str, Any],
        parent_logger: Optional[logging.Logger] = None,
    ):
        # --- TELEMETRY SYNC ---
        if parent_logger:
            self.logger = parent_logger.getChild("filter")
            self.logger.setLevel(parent_logger.level)
        else:
            self.logger = logging.getLogger("filter")
            self.logger.setLevel(logging.INFO)

        self.root = Path(root_dir).resolve()
        self.registry = language_definitions

        # 1. Configuration Binding
        self.config = aperture_config or {}

        # 2. Extract Spectral Bands & Black Holes
        self.bands = self.config.get(
            "BANDS",
            {
                "RADIO": "radio_noise",
                "MICROWAVE": "binary_debris",
                "DARK_MATTER": "unknown_ext",
                "INFRARED": "saturated",
                "VISIBLE": "source_code",
                "QUARANTINE": "quarantine",
            },
        )

        self.black_holes = set(self.config.get("BLACK_HOLES", set()))
        self.black_hole_exts = set(self.config.get("BLACK_HOLE_EXTENSIONS", set()))
        self.contraband_patterns = self.config.get("CONTRABAND_PATTERNS", [])

        # ---> THE AUTO-GEN DOC SHIELD (Heuristic Core) <---
        self.doc_generator_shield = re.compile(
            r'<meta\s+name=["\']generator["\']\s+content=["\'](?:jazzy|Doxygen|Sphinx|JSDoc|TypeDoc|appledoc|Docco|MkDocs|Hugo|DocFX|Docgen).*?["\']'
        )

        # ---> THE MACHINE-GENERATED SOURCE SHIELD <---
        self.machine_gen_shield = re.compile(
            r"(?i)(?:<auto-generated>|\bdo not edit\b|auto-generated|automatically generated|this file is generated|generated by \S+)"
        )

        # ---> THE SEMANTIC PATH SHIELD (Replaces Hardcoded Folders) <---
        # Matches boundaries commonly associated with generated, build, vendor, and noise directories.
        self.infra_path_shield = re.compile(
            r"(?i)[-_./\\]?(?:gen|generated|build|dist|out|vendor|mock|test|spec|docs|assets|scripts|__monolith__|__snapshots__|.github|.gitlab|node_modules|third[-_]?party|deps?|lib(?:rary|raries)?)[-_./\\]?\b"
        )

        # --- STATE CACHE & DYNAMIC STATE ---
        self._intent_cache: Set[str] = set()
        self.dynamic_black_holes: Set[str] = set()

        self.logger.debug(f"Initializing Solar Shield for sector: '{self.root.name}'...")

        # 3. Optimized Lookup Construction
        self.whitelisted_extensions: Set[str] = set()
        self.ecosystem_anchors: Set[str] = set()

        for lang_id, data in self.registry.items():
            self.whitelisted_extensions.update(data.get("extensions", []))
            self.ecosystem_anchors.update(data.get("exact_matches", []))

        self.ignore_patterns = self._load_gitignore_patterns()

        self.logger.info(
            f"Dispatching Survey Probe to Sector '{self.root.name}' | "
            f"Tracking {len(self.whitelisted_extensions)} spectral bands."
        )

    def evaluate_path_integrity(self, file_path: Union[str, Path], has_intent: bool = False) -> Tuple[bool, int, str]:
        """
        [PHASE 0 ENTRY POINT]
        Performs high-speed path analysis to build the CensusArray (Radar Walk).
        Determines if a file is physically valid before any I/O occurs.
        """
        path_obj = Path(file_path)
        normalized_path = path_obj.as_posix()
        _, ext = os.path.splitext(path_obj.name)

        try:
            relative_path = path_obj.relative_to(self.root).as_posix()
        except ValueError:
            relative_path = normalized_path

        try:
            size_bytes = path_obj.stat().st_size if path_obj.exists() else 0
        except OSError:
            size_bytes = 0

        # --- TIER 0.1: THE SECRETS RADAR ---
        if path_obj.name in self.config.get("SECRETS_EXACT", set()) or ext.lower() in self.config.get(
            "SECRETS_EXTENSIONS", set()
        ):
            reason = f"CRITICAL LEAK (Exposed Secret: '{path_obj.name}')"
            return False, size_bytes, reason

        # --- TIER 0.2: THE NEURAL AUDITOR SHUNT (Model Weights) ---
        AI_MODEL_EXTS = {
            ".safetensors",
            ".gguf",
            ".onnx",
            ".pt",
            ".pth",
            ".bin",
            ".tflite",
            ".pb",
            ".h5",
        }
        if ext.lower() in AI_MODEL_EXTS:
            reason = f"AI MODEL WEIGHTS (Bypassing Standard Logic: '{ext}')"
            self.logger.info(f"🧠 NEURAL AUDITOR SHUNT: Routing {path_obj.name} away from regex engines.")
            return False, size_bytes, reason

        # --- TIER 0.5: THE ABSOLUTE EXTENSION SHIELD ---
        if ext.lower() in self.black_hole_exts and ext.lower() not in self.whitelisted_extensions:
            reason = f"Blocked (Explicitly Blacklisted Extension: '{ext}')"
            return False, size_bytes, reason

        # Establish Intent Lock
        active_intent = has_intent or (normalized_path in self._intent_cache)
        if active_intent:
            self._intent_cache.add(normalized_path)

        # --- TIER 1: THE SOLAR SHIELD ---
        if not self._check_solar_shield(relative_path, has_intent=active_intent):
            reason = "Blocked (System Exclusion, Hidden Directory, or Dynamic Black Hole)"
            return False, size_bytes, reason

        # --- TIER 2: THE VISIBLE SPECTRUM ---
        if active_intent:
            return True, size_bytes, "Passed (GuideStar Intent Lock)"

        if not ext:
            return True, size_bytes, "Passed (Extensionless -> Subject to Shebang scan)"

        if path_obj.name in self.ecosystem_anchors or ext.lower() in self.whitelisted_extensions:
            return True, size_bytes, "Passed (Whitelisted)"

        reason = f"Blocked (Unsupported Extension: '{ext}')"
        return False, size_bytes, reason

    def is_in_scope(
        self,
        file_path: Union[str, Path],
        content: Optional[str] = None,
        has_intent: bool = False,
    ) -> FilterResult:
        """
        [PHASE 1 ENTRY POINT]
        The final Content Gate. Validates the physical matter of the artifact
        to ensure it is not binary, minified, or auto-generated debris.
        """
        path_obj = Path(file_path)
        normalized_path = path_obj.as_posix()
        relative_path = str(path_obj.relative_to(self.root)) if path_obj.is_relative_to(self.root) else normalized_path
        active_intent = has_intent or (normalized_path in self._intent_cache)

        result: FilterResult = {
            "is_in_scope": False,
            "band": self.bands.get("VISIBLE", "source_code"),
            "reason": None,
            "path": normalized_path,
            "size_bytes": 0,
            "total_loc": 0,
        }

        try:
            if not path_obj.exists():
                raise InaccessibleArtifactError("Artifact missing on disk")

            stats = path_obj.stat()
            result["size_bytes"] = stats.st_size

            # --- TIER 0: Resource Guarding ---
            max_mb = self.config.get("MAX_FILE_SIZE_MB", 10)
            if stats.st_size > (max_mb * 1024 * 1024):
                result.update(
                    {
                        "band": self.bands.get("INFRARED", "saturated"),
                        "reason": f"Blocked (File size exceeds {max_mb}MB limit)",
                    }
                )
                return result

            # --- TIER 1 & 2: Path Gate ---
            is_valid, size_bytes, reason = self.evaluate_path_integrity(path_obj, has_intent=active_intent)

            if not is_valid:
                result.update({"band": self.bands.get("RADIO"), "reason": reason})
                return result

            # --- THE SHUNT: Content Bypass for Secrets ---
            if reason and "CRITICAL LEAK" in reason:
                result.update(
                    {
                        "is_in_scope": True,
                        "band": self.bands.get("VISIBLE", "source_code"),
                        "reason": reason,
                        "total_loc": len(content.splitlines()) if content else 0,
                    }
                )
                return result

            # --- TIER 3 & 4: Content Gate ---
            if content is None:
                result["reason"] = "Protocol Violation: Missing content buffer"
                return result

            integrity = self._check_artifact_integrity(content, relative_path, has_intent=active_intent)
            result["total_loc"] = integrity["loc"]

            if not integrity["valid"]:
                result.update({"band": integrity["band"], "reason": integrity["reason"]})
                return result

            # --- MISSION SUCCESS ---
            result["is_in_scope"] = True
            return result

        except Exception as e:
            self.logger.error(f"Filter Collision on '{relative_path}': {str(e)}")
            result["reason"] = f"Internal Exception: {str(e)}"
            return result

    def _check_artifact_integrity(self, content: str, rel_path: str, has_intent: bool = False) -> Dict[str, Any]:
        """
        Deep-scans the content buffer for corruption, binary data, arrays,
        or documentation generator signatures.
        """
        report = {
            "valid": True,
            "band": self.bands.get("VISIBLE", "source_code"),
            "reason": None,
            "loc": 0,
        }

        # Split lines early so we can use LOC for all heuristics
        lines_list = content.splitlines()
        report["loc"] = len(lines_list)

        # --- TIER 3: Opaque Binary Detection ---
        if "\x00" in content:
            report.update(
                {
                    "valid": False,
                    "band": self.bands.get("MICROWAVE", "binary_debris"),
                    "reason": "Blocked (Binary Format Detected)",
                }
            )
            return report

        # --- TIER 3.1: THE MONOLITH AMALGAMATION SHIELD ---
        # 30,000+ lines in a single file is an amalgamation (e.g. sqlite3.c) or massive test array.
        # It will saturate and choke the standard regex engine. Override Intent.
        if report["loc"] > 30000:
            report.update(
                {
                    "valid": False,
                    "band": self.bands.get("INFRARED", "saturated"),
                    "reason": f"Blocked (Monolithic Amalgamation: {report['loc']} LOC exceeds safe regex boundaries)",
                }
            )
            return report

        # --- TIER 3.5: THE AUTO-GEN DOC SHIELD ---
        low_path = rel_path.lower()
        if low_path.endswith((".html", ".htm", ".xml")):
            head_sample = "\n".join(lines_list[:100])
            if self.doc_generator_shield.search(head_sample):
                parent_dir = str(Path(rel_path).parent)
                if parent_dir != ".":
                    self.dynamic_black_holes.add(parent_dir)
                    self.logger.debug(f"Dynamic Infection: Directory '{parent_dir}' flagged as Doc Debris.")

                report.update(
                    {
                        "valid": False,
                        "band": self.bands.get("RADIO", "radio_noise"),
                        "reason": "Blocked (Machine-Generated Documentation Signature)",
                    }
                )
                return report

        # --- TIER 3.6: THE MACHINE-GENERATED SOURCE SHIELD ---
        head_sample = "\n".join(lines_list[:100])
        if self.machine_gen_shield.search(head_sample):
            if not has_intent or report["loc"] > 1000:
                report.update(
                    {
                        "valid": False,
                        "band": self.bands.get("RADIO", "radio_noise"),
                        "reason": f"Blocked (Machine-Generated Source Code Signature: {report['loc']} LOC)",
                    }
                )
                return report

        # --- TIER 3.7: THE LEXICAL MONOTONY SHIELD (Generated Code) ---
        if report["loc"] > 2000 and not has_intent and not low_path.endswith((".cpy", ".cbl", ".cob")):
            sample_lines = lines_list[:500]
            meaningful_lines = [l for l in sample_lines if l.strip()]

            if len(meaningful_lines) > 100:
                indent_counts = {}
                for l in meaningful_lines:
                    indent = len(l) - len(l.lstrip())
                    indent_counts[indent] = indent_counts.get(indent, 0) + 1

                max_indent_freq = max(indent_counts.values())
                if (max_indent_freq / len(meaningful_lines)) > 0.85:
                    report.update(
                        {
                            "valid": False,
                            "band": self.bands.get("RADIO", "radio_noise"),
                            "reason": f"Blocked (Lexical Monotony: High structural repetition detected in {report['loc']} LOC)",
                        }
                    )
                    return report

        # --- TIER 3.8: THE DECLARATIVE & VECTOR DATA SHIELD ---
        if low_path.endswith((".yml", ".yaml", ".json", ".xml", ".svg", ".sql", ".csv", ".tsv")):
            # If the file is massive, absolutely drop it. Even if Git tracks it.
            if report["loc"] > 2500:
                report.update(
                    {
                        "valid": False,
                        "band": self.bands.get("RADIO", "radio_noise"),
                        "reason": f"Blocked (Massive Declarative/Vector Blob: {report['loc']} LOC)",
                    }
                )
                return report
            elif not has_intent and report["loc"] > 1000:
                report.update(
                    {
                        "valid": False,
                        "band": self.bands.get("RADIO", "radio_noise"),
                        "reason": f"Blocked (Declarative Data Blob without Intent: {report['loc']} LOC)",
                    }
                )
                return report

        # --- TIER 3.9: THE TEST DATA & ARRAY SHIELD ---
        # Drops massive test vectors, crypto keys, or arrays compiled into headers/tests.
        if report["loc"] > 500:
            # Check 1: Hex Arrays
            hex_count = content.count("0x") + content.count("0X")
            if hex_count > report["loc"]:
                report.update(
                    {
                        "valid": False,
                        "band": self.bands.get("MICROWAVE", "binary_debris"),
                        "reason": f"Blocked (Embedded Hex Payload: {hex_count} hex tokens in {report['loc']} LOC)",
                    }
                )
                return report

            # Check 2: Massive Data Arrays (Comma Density)
            # If there are more than 3 commas per line on average in a massive file, it's a data array/matrix.
            comma_count = content.count(",")
            if comma_count > (report["loc"] * 3):
                report.update(
                    {
                        "valid": False,
                        "band": self.bands.get("MICROWAVE", "binary_debris"),
                        "reason": f"Blocked (Embedded Array/Matrix Payload: {comma_count} commas in {report['loc']} LOC)",
                    }
                )
                return report

        # --- TIER 4: INFRARED GATE (Minification & Saturation) ---
        max_line = self.config.get("MAX_LINE_LENGTH", 500)

        is_prose = low_path.endswith((".md", ".markdown", ".txt", ".json", ".csv", ".rst", ".sql", ".svg"))

        for i, line in enumerate(lines_list[:100]):
            if len(line) > max_line and not is_prose:
                report.update(
                    {
                        "valid": False,
                        "band": self.bands.get("INFRARED", "saturated"),
                        "reason": f"Blocked (Saturation: Line {i+1} exceeds {max_line} chars)",
                    }
                )
                return report

        return report

    def _check_solar_shield(self, rel_path: str, has_intent: bool = False) -> bool:
        """
        Determines if the path is in a blocked, ignored, or dynamically
        infected sector. Implements the 'Contraband Shield' and 'Infrastructure Shield'.
        """
        parts = rel_path.split("/")

        # 1. Static Black Holes & Hidden Paths
        for part in parts:
            low_part = part.lower()
            if low_part in self.black_holes:
                return False

            if part.startswith(".") and part not in self.ecosystem_anchors:
                if not has_intent:
                    return False

        # --- THE DYNAMIC DOC DEBRIS SHIELD ---
        path_obj = Path(rel_path)
        for parent in path_obj.parents:
            if str(parent) in self.dynamic_black_holes:
                self.logger.debug(f"Dynamic Deflection: Asset '{rel_path}' blocked in infected directory.")
                return False

        # 2. Semantic Infrastructure & Test Target Shield
        if self.infra_path_shield.search(rel_path):
            if not has_intent:
                return False

        # 3. The Contraband Shield (Vendor Blob Deflection)
        filename = parts[-1]
        for pattern in self.contraband_patterns:
            if fnmatch.fnmatch(filename, pattern):
                return False

        # 4. Standard Iterative Gitignore Logic (The Fix)
        for pattern in self.ignore_patterns:
            if pattern.endswith("/"):
                if any(fnmatch.fnmatch(p + "/", pattern) for p in parts):
                    return False
            else:
                if fnmatch.fnmatch(rel_path, pattern) or fnmatch.fnmatch(filename, pattern):
                    return False

        return True

    def _load_gitignore_patterns(self) -> List[str]:
        """Reads local .gitignore files to identify Radio Noise."""
        patterns = []
        ignore_file = self.root / ".gitignore"

        if ignore_file.exists():
            try:
                with ignore_file.open("r", encoding="utf-8") as f:
                    for line in f:
                        l = line.strip()
                        if l and not l.startswith("#"):
                            patterns.append(l)
            except Exception as e:
                self.logger.warning(f"Failed to parse .gitignore: {e}")

        return patterns
