#!/usr/bin/env python3
# ==============================================================================
# GitGalaxy Spoke: Zero-Trust JCL Forge (v5 - Hygienic Defaults)
# ==============================================================================
import argparse
import sys
import re
from pathlib import Path
from datetime import datetime

def analyze_cobol_intent(filepath: Path) -> dict:
    intent = {
        "program_id": "UNKNOWN", 
        "files_requested": [], 
        "is_cics": False, 
        "is_db2": False,
        "cics_calls": 0,
        "sql_calls": 0
    }
    
    try:
        raw_content = filepath.read_text(encoding='utf-8', errors='ignore')
        
        # 1. THE FLATTENER: Strip punch-card formatting
        clean_lines = []
        for line in raw_content.splitlines():
            if len(line) > 6 and line[6] in ('*', '/'): 
                continue
            clean_lines.append(line[7:] if len(line) > 7 else line)
            
        monolith_code = " ".join(clean_lines)

        # 2. EXTRACT PROGRAM-ID (With fallback to file name)
        prog_id_match = re.search(r'PROGRAM-ID\.\s+[\'"]?([A-Z0-9\-]+)[\'"]?', monolith_code, re.IGNORECASE)
        if prog_id_match: 
            intent["program_id"] = prog_id_match.group(1).strip()
        else:
            intent["program_id"] = filepath.stem.upper()

        # 3. BATCH I/O: Extract all File Assignments
        file_assign_pattern = re.compile(r'SELECT\s+([A-Z0-9\-]+)\s+ASSIGN\s+(?:TO\s+)?([A-Z0-9\-]+)[^.]*\.', re.IGNORECASE)
        for match in file_assign_pattern.finditer(monolith_code):
            internal_name = match.group(1).strip()
            raw_dd = match.group(2).strip()
            clean_dd = re.sub(r'^(?:UT|UR)-S-', '', raw_dd)
            intent["files_requested"].append({"internal": internal_name, "dd_name": clean_dd})

        # 4. TRANSACTIONAL I/O: Detect EXEC CICS blocks
        cics_matches = re.findall(r'EXEC\s+CICS.*?END-EXEC\.', monolith_code, re.IGNORECASE)
        if cics_matches:
            intent["is_cics"] = True
            intent["cics_calls"] = len(cics_matches)

        # 5. DATABASE I/O: Detect EXEC SQL blocks
        sql_matches = re.findall(r'EXEC\s+SQL.*?END-EXEC\.', monolith_code, re.IGNORECASE)
        if sql_matches:
            intent["is_db2"] = True
            intent["sql_calls"] = len(sql_matches)
            
    except Exception as e: 
        print(f"  [!] Intent Forge Error on {filepath.name}: {e}")
        
    return intent

def generate_zero_trust_jcl(intent: dict, job_name: str, account_code: str, lineage: dict = None, corporate_header: str = "") -> str:
    if lineage is None: lineage = {"inputs": set(), "outputs": set()}
    prog_name = intent["program_id"]
    jcl = []
    
    jcl.append(f"//{job_name} JOB ({account_code}),'GITGALAXY FORGE',")
    jcl.append(f"//             CLASS=A,MSGCLASS=A,MSGLEVEL=(1,1),")    
    jcl.append(f"//             USER=HERC01,PASSWORD=CUL8TR,")
    jcl.append(f"//             TIME=10,REGION=4M")
    jcl.append(f"//* ==========================================================")
    jcl.append(f"//* AUTOGENERATED BY GITGALAXY ZERO-TRUST FORGE")
    
    arch_flags = []
    if intent["is_cics"]: arch_flags.append("CICS")
    if intent["is_db2"]: arch_flags.append("DB2")
    if arch_flags:
        jcl.append(f"//* ARCHITECTURE REQUIRES: {' + '.join(arch_flags)}")
        
    jcl.append(f"//* ==========================================================")
    jcl.append(f"//STEP01   EXEC PGM={prog_name}")
    jcl.append(f"//STEPLIB  DD DSN=HERC01.LOADLIB,DISP=SHR")
    jcl.append(f"//SYSOUT   DD SYSOUT=*")
    jcl.append(f"//SYSPRINT DD SYSOUT=*")
    jcl.append(f"//SYSUDUMP DD SYSOUT=*")
    
    if intent["files_requested"]:
        jcl.append(f"//* --- EXTRACTED FILE INTENT BOUNDARIES ---")
        for file in intent["files_requested"]:
            raw_dd = file["dd_name"]
            dd = re.sub(r'[^A-Z0-9]', '', raw_dd.upper())
            if len(dd) > 8: dd = dd[-8:]
            
            if raw_dd in lineage.get('outputs', set()): disp = "(NEW,CATLG,DELETE)"
            elif raw_dd in lineage.get('inputs', set()): disp = "SHR"
            else: disp = "SHR"
            
            jcl.append(f"//{dd.ljust(8)} DD DSN=HERC01.DATA.{dd},")
            if "NEW" in disp:
                jcl.append(f"//             DISP={disp},")
                jcl.append(f"//             UNIT=SYSDA,")
                jcl.append(f"//             SPACE=(CYL,(5,1),RLSE),")
                jcl.append(f"//             DCB=(LRECL=80,RECFM=FB,BLKSIZE=800)")
            else:
                jcl.append(f"//             DISP={disp}")
                if "SHR" in disp and raw_dd not in lineage.get('inputs', set()):
                    jcl.append(f"//* WARNING: NO EXPLICIT OPEN INTENT FOR {dd}")
    jcl.append("//")
    return "\n".join(jcl)

def main():
    parser = argparse.ArgumentParser(description="GitGalaxy Zero-Trust JCL Forge (v5)")
    parser.add_argument("target", help="Target directory or specific COBOL file")
    parser.add_argument("--job", default="GITGJOB", help="Job name for the generated JCL")
    parser.add_argument("--acct", default="12345", help="Account code for the generated JCL")
    parser.add_argument("--out", type=str, help="Output directory (default: hygienic timestamped folder)")
    args = parser.parse_args()

    target_path = Path(args.target).resolve()
    
    if target_path.is_dir():
        extensions = ("*.cbl", "*.CBL", "*.cob", "*.COB", "*.ccp", "*.CCP")
        cobol_files = []
        for ext in extensions:
            cobol_files.extend(target_path.rglob(ext))
    else:
        cobol_files = [target_path]

    if not cobol_files:
        print(f"\n[!] ERROR: No COBOL source files found in: {target_path}")
        sys.exit(1)

    # --- THE HYGIENIC DEFAULT LOGIC ---
    if args.out:
        out_dir = Path(args.out).resolve()
    else:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        if target_path.is_dir():
            # e.g., cics-genapp -> cics-genapp_forged_20260425_161559
            out_dir = target_path.parent / f"{target_path.name}_forged_{timestamp}"
        else:
            out_dir = target_path.parent / f"forged_jcls_{timestamp}"

    # Create the directory
    out_dir.mkdir(parents=True, exist_ok=True)

    print("\n==============================================================")
    print(" 🚀 GitGalaxy Spoke: Zero-Trust JCL Forge (v5)")
    print("==============================================================")
    print(f" [*] Target Path : {target_path}")
    print(f" [*] Output Dir  : {out_dir}")
    print(f" [*] Files Found : {len(cobol_files)}")
    print("--------------------------------------------------------------")

    success_count = 0
    for file_path in cobol_files:
        intent = analyze_cobol_intent(file_path)
        jcl_output = generate_zero_trust_jcl(intent, args.job[:8].upper(), args.acct)
        
        # Output strictly locked to the designated hygienic folder
        out_path = out_dir / f"{intent['program_id']}.jcl"
        out_path.write_text(jcl_output, encoding='utf-8')
        
        io_parts = []
        if len(intent['files_requested']) > 0: 
            io_parts.append(f"{len(intent['files_requested'])} Batch I/O")
        if intent['cics_calls'] > 0: 
            io_parts.append(f"{intent['cics_calls']} CICS")
        if intent['sql_calls'] > 0: 
            io_parts.append(f"{intent['sql_calls']} SQL")
            
        io_str = f"({', '.join(io_parts)})" if io_parts else "(No I/O)"
        
        print(f"  [+] Forged: {file_path.name.ljust(15)} -> {out_path.name.ljust(15)} {io_str}")
        success_count += 1

    print("--------------------------------------------------------------")
    print(f" [✓] Done! Successfully forged {success_count} JCL(s).")
    print("==============================================================\n")

if __name__ == "__main__": 
    main()