#!/usr/bin/env python3
# ==============================================================================
# GitGalaxy Spoke: Zero-Trust JCL Forge (v3 - IR Context Aware)
# ==============================================================================
import argparse
import sys
import re
from pathlib import Path

def analyze_cobol_intent(filepath: Path) -> dict:
    intent = {"program_id": "UNKNOWN", "files_requested": [], "is_cics": False, "is_db2": False}
    
    try:
        raw_content = filepath.read_text(encoding='utf-8', errors='ignore')
        
        # 1. THE FLATTENER: Strip punch-card formatting and merge into a single AST string
        clean_lines = []
        for line in raw_content.splitlines():
            # Skip pure comment lines (Asterisk or Slash in Column 7)
            if len(line) > 6 and line[6] in ('*', '/'): 
                continue
            # Keep only Column 8 and beyond (The actual code)
            clean_lines.append(line[7:] if len(line) > 7 else line)
            
        # Join with spaces so multi-line statements become a single continuous sentence
        monolith_code = " ".join(clean_lines)

        # 2. EXTRACT PROGRAM-ID (Bounded by the period)
        prog_id_match = re.search(r'PROGRAM-ID\.\s+([A-Z0-9\-]+)\.', monolith_code, re.IGNORECASE)
        if prog_id_match: 
            intent["program_id"] = prog_id_match.group(1).strip()

        # 3. MULTI-LINE REGEX: Extract all File Assignments (Bounded by the period)
        # This will now successfully catch SELECT and ASSIGN TO even if they are 20 lines apart!
        file_assign_pattern = re.compile(r'SELECT\s+([A-Z0-9\-]+)\s+ASSIGN\s+(?:TO\s+)?([A-Z0-9\-]+)[^.]*\.', re.IGNORECASE)
        
        for match in file_assign_pattern.finditer(monolith_code):
            internal_name = match.group(1).strip()
            raw_dd = match.group(2).strip()
            
            # Strip IBM system prefixes like UT-S- or UR-S-
            clean_dd = re.sub(r'^(?:UT|UR)-S-', '', raw_dd)
            
            intent["files_requested"].append({
                "internal": internal_name, 
                "dd_name": clean_dd
            })
            
    except Exception as e: 
        print(f"  [!] Intent Forge Error on {filepath.name}: {e}")
        
    return intent

def generate_zero_trust_jcl(intent: dict, job_name: str, account_code: str, lineage: dict = None, corporate_header: str = "") -> str:
    if lineage is None: lineage = {"inputs": set(), "outputs": set()}
    prog_name = intent["program_id"]
    jcl = []
    
    jcl.append(f"//{job_name} JOB ({account_code}),'GITGALAXY FORGE',")
    jcl.append(f"//             CLASS=A,MSGCLASS=A,MSGLEVEL=(1,1),")    
    jcl.append(f"//             USER=HERC01,PASSWORD=CUL8TR,")
    jcl.append(f"//             TIME=10,REGION=4M")
    jcl.append(f"//* ==========================================================")
    jcl.append(f"//* AUTOGENERATED BY GITGALAXY ZERO-TRUST FORGE")
    jcl.append(f"//* ==========================================================")
    
    jcl.append(f"//STEP01   EXEC PGM={prog_name}")
    # Point to the new Superuser directory!
    jcl.append(f"//STEPLIB  DD DSN=HERC01.LOADLIB,DISP=SHR")
    
    jcl.append(f"//SYSOUT   DD SYSOUT=*")
    jcl.append(f"//SYSPRINT DD SYSOUT=*")
    jcl.append(f"//SYSUDUMP DD SYSOUT=*")
    
    if intent["files_requested"]:
        jcl.append(f"//* --- EXTRACTED FILE INTENT BOUNDARIES ---")
        for file in intent["files_requested"]:
            raw_dd = file["dd_name"]
            dd = re.sub(r'[^A-Z0-9]', '', raw_dd.upper())
            if len(dd) > 8: dd = dd[-8:]
            
            if raw_dd in lineage.get('outputs', set()): disp = "(NEW,CATLG,DELETE)"
            elif raw_dd in lineage.get('inputs', set()): disp = "SHR"
            else: disp = "SHR"
            
            jcl.append(f"//{dd.ljust(8)} DD DSN=HERC01.DATA.{dd},")
            if "NEW" in disp:
                jcl.append(f"//             DISP={disp},")
                jcl.append(f"//             UNIT=SYSDA,")
                jcl.append(f"//             SPACE=(CYL,(5,1),RLSE),")
                jcl.append(f"//             DCB=(LRECL=80,RECFM=FB,BLKSIZE=800)")
            else:
                jcl.append(f"//             DISP={disp}")
                if "SHR" in disp and raw_dd not in lineage.get('inputs', set()):
                    # Warning moved to own line to respect punch-card Col 71
                    jcl.append(f"//* WARNING: NO EXPLICIT OPEN INTENT FOR {dd}")
    jcl.append("//")
    return "\n".join(jcl)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("target")
    parser.add_argument("--job", default="GITGJOB")
    parser.add_argument("--acct", default="12345")
    parser.add_argument("--out", type=str)
    args = parser.parse_args()

    target_path = Path(args.target).resolve()
    cobol_files = list(target_path.rglob("*.cbl")) if target_path.is_dir() else [target_path]

    out_dir = Path(args.out).resolve() if args.out else None
    if out_dir: out_dir.mkdir(parents=True, exist_ok=True)

    for file_path in cobol_files:
        intent = analyze_cobol_intent(file_path)
        jcl_output = generate_zero_trust_jcl(intent, args.job[:8].upper(), args.acct)
        out_path = out_dir / f"{intent['program_id']}.jcl" if out_dir else file_path.parent / f"{intent['program_id']}.jcl"
        out_path.write_text(jcl_output, encoding='utf-8')
if __name__ == "__main__": main()