#!/usr/bin/env python3
# ==============================================================================
# GitGalaxy Spoke: Zero-Trust JCL Forge (Legacy Lens)
# Purpose: Structurally analyzes COBOL intent and generates least-privilege 
#          mainframe Job Control Language (JCL) execution scripts.
# ==============================================================================
import argparse
import sys
import re
from pathlib import Path

def analyze_cobol_intent(filepath: Path) -> dict:
    """Uses positional regex to extract the functional intent of a COBOL program."""
    intent = {
        "program_id": "UNKNOWN",
        "files_requested": [],
        "is_cics": False,  # Transactional web/screen logic
        "is_db2": False    # SQL Database logic
    }
    
    # Regex designed for COBOL's punch-card positional formatting
    prog_id_pattern = re.compile(r'^.{6} PROGRAM-ID\.\s+([A-Z0-9\-]+)\.', re.IGNORECASE)
    file_assign_pattern = re.compile(r'^.{6}\s+SELECT\s+([A-Z0-9\-]+)\s+ASSIGN\s+TO\s+([A-Z0-9\-]+)', re.IGNORECASE)
    
    with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            # Skip empty lines or COBOL comments (asterisk in column 7)
            if len(line) < 7 or line[6] == '*':
                continue
                
            # Extract Program Name
            id_match = prog_id_pattern.search(line)
            if id_match:
                intent["program_id"] = id_match.group(1).strip()
                
            # Extract File I/O Intent
            file_match = file_assign_pattern.search(line)
            if file_match:
                internal_name = file_match.group(1).strip()
                external_dd = file_match.group(2).strip()
                intent["files_requested"].append({"internal": internal_name, "dd_name": external_dd})
                
            # Detect external integrations
            if "EXEC CICS" in line:
                intent["is_cics"] = True
            if "EXEC SQL" in line:
                intent["is_db2"] = True
                
    return intent

def generate_zero_trust_jcl(intent: dict, job_name: str, account_code: str) -> str:
    """Forges a locked-down JCL script based strictly on the extracted intent."""
    prog_name = intent["program_id"]
    
    jcl = []
    jcl.append(f"//{job_name} JOB ({account_code}),'GITGALAXY FORGE',")
    jcl.append(f"//             CLASS=A,MSGCLASS=X,MSGLEVEL=(1,1),")
    
    # Zero-Trust Constraints: Hard cap on runtime (10 mins) and memory (4MB)
    jcl.append(f"//             TIME=10,REGION=4M")
    jcl.append(f"//* ==========================================================")
    jcl.append(f"//* AUTOGENERATED BY GITGALAXY ZERO-TRUST FORGE")
    jcl.append(f"//* TARGET PROGRAM : {prog_name}")
    if intent["is_db2"]: jcl.append(f"//* SUBSYSTEMS     : DB2 SQL DETECTED")
    if intent["is_cics"]: jcl.append(f"//* SUBSYSTEMS     : CICS DETECTED")
    jcl.append(f"//* ==========================================================")
    
    jcl.append(f"//STEP01   EXEC PGM={prog_name}")
    jcl.append(f"//STEPLIB  DD DSN=PROD.LOADLIB,DISP=SHR")
    
    # Standard Mainframe I/O
    jcl.append(f"//SYSOUT   DD SYSOUT=*")
    jcl.append(f"//SYSPRINT DD SYSOUT=*")
    jcl.append(f"//SYSUDUMP DD SYSOUT=*")
    
    # Least-Privilege Data Definitions (DDs)
    if intent["files_requested"]:
        jcl.append(f"//* --- EXTRACTED FILE INTENT BOUNDARIES ---")
        for file in intent["files_requested"]:
            dd = file["dd_name"]
            # Generate a strict, placeholder DD card for the required file
            jcl.append(f"//{dd.ljust(8)} DD DSN=PROD.DATA.{dd},")
            jcl.append(f"//             DISP=(NEW,CATLG,DELETE),")
            jcl.append(f"//             SPACE=(CYL,(5,1),RLSE)")
            
    return "\n".join(jcl)

def main():
    parser = argparse.ArgumentParser(description="GitGalaxy COBOL Zero-Trust JCL Forge")
    parser.add_argument("target", help="Path to a .cbl file OR a directory to scan")
    parser.add_argument("--job", default="GITGJOB", help="Job name for the JCL card (max 8 chars)")
    parser.add_argument("--acct", default="12345", help="Mainframe accounting code")
    parser.add_argument("--out", type=str, help="Optional: Custom directory to save all forged JCLs")
    args = parser.parse_args()

    target_path = Path(args.target).resolve()
    if not target_path.exists():
        print(f"Error: Target {target_path} does not exist.")
        sys.exit(1)

    # Automatically handle either a single file or a massive directory hunt
    cobol_files = []
    if target_path.is_file():
        cobol_files.append(target_path)
    elif target_path.is_dir():
        print(f"📠 GitGalaxy Legacy Lens scanning directory: {target_path.name}...")
        cobol_files.extend(target_path.rglob("*.cbl"))
        cobol_files.extend(target_path.rglob("*.cob"))

    if not cobol_files:
        print("⚠️ No .cbl or .cob files found in the target location.")
        sys.exit(0)

    print(f"🔎 Found {len(cobol_files)} COBOL payloads. Forging Zero-Trust constraints...\n")

    # Setup the output directory if provided
    if args.out:
        out_dir = Path(args.out).resolve()
        out_dir.mkdir(parents=True, exist_ok=True)

    for file_path in cobol_files:
        # 1. X-Ray the COBOL
        intent = analyze_cobol_intent(file_path)
        
        # 2. Forge the JCL
        jcl_output = generate_zero_trust_jcl(intent, args.job[:8].upper(), args.acct)
        
        # 3. Save Artifact (Diverts to the out_dir if the flag was used)
        if args.out:
            out_path = out_dir / f"{intent['program_id']}.jcl"
        else:
            out_path = file_path.parent / f"{intent['program_id']}.jcl"
            
        with open(out_path, 'w', encoding='utf-8') as f:
            f.write(jcl_output)
            
        print(f" 🛡️ FORGED: {intent['program_id'].ljust(10)} -> Locked {len(intent['files_requested'])} I/O Boundaries")

    print("\n" + "="*60)
    print(f" ✅ OPERATION COMPLETE: {len(cobol_files)} Zero-Trust JCL scripts generated.")
    if args.out:
        print(f" 📁 Saved to: {out_dir}")
    print("="*60 + "\n")

if __name__ == "__main__":
    main()
